// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry } from "@furo/open-models/dist/index";

import {
  CubeEntity as Furoui5TestCubeCubeEntity,
  type ICubeEntity as IFuroui5TestCubeCubeEntity,
  type TCubeEntity as TFuroui5TestCubeCubeEntity,
} from "./CubeEntity";

/**
 * @interface ICubeServiceUpdateResponse
 */
export interface ICubeServiceUpdateResponse {
  entity?: IFuroui5TestCubeCubeEntity;
}

/**
 * @interface TCubeServiceUpdateResponse
 */
export interface TCubeServiceUpdateResponse {
  entity?: TFuroui5TestCubeCubeEntity;
}

/**
 * CubeServiceUpdateResponse
 */
export class CubeServiceUpdateResponse extends FieldNode {
  private _entity: Furoui5TestCubeCubeEntity;

  public __defaultValues: ICubeServiceUpdateResponse;

  constructor(initData?: ICubeServiceUpdateResponse, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furoui5test.cube.CubeServiceUpdateResponse";

    this.__meta.nodeFields = [
      {
        fieldName: "entity",
        protoName: "entity",
        FieldConstructor: Furoui5TestCubeCubeEntity,
        constraints: {},
      },
    ];

    // Initialize the fields
    this._entity = new Furoui5TestCubeCubeEntity(undefined, this, "entity");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceUpdateResponse] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof CubeServiceUpdateResponse] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  public get entity(): Furoui5TestCubeCubeEntity {
    return this._entity;
  }

  public set entity(v: IFuroui5TestCubeCubeEntity) {
    this.__TypeSetter(this._entity, v);
  }

  fromLiteral(data: ICubeServiceUpdateResponse) {
    super.__fromLiteral(data);
  }

  toLiteral(): ICubeServiceUpdateResponse {
    return super.__toLiteral();
  }
}

Registry.register("furoui5test.cube.CubeServiceUpdateResponse", CubeServiceUpdateResponse);
