// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { BOOLEAN, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface IFloatLabelsEntry
 */
export interface IFloatLabelsEntry {
  key?: string;
  value?: boolean;
}

/**
 * @interface TFloatLabelsEntry
 */
export interface TFloatLabelsEntry {
  key?: string;
  value?: boolean;
}

/**
 * FloatLabelsEntry
 */
export class FloatLabelsEntry extends FieldNode {
  /**
   **/
  private _key: STRING;

  /**
   **/
  private _value: BOOLEAN;

  public __defaultValues: IFloatLabelsEntry;

  constructor(initData?: IFloatLabelsEntry, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.fat.Float.LabelsEntry";
    this.__meta.description = "FloatLabelsEntry";

    this.__meta.nodeFields = [
      {
        fieldName: "key",
        protoName: "key",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._key = new STRING(undefined, this, "key");

    /**
     **/
    this._value = new BOOLEAN(undefined, this, "value");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof FloatLabelsEntry] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof FloatLabelsEntry] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get key(): STRING {
    return this._key;
  }

  /**
   * The setter receives `string`
   **/
  public set key(v: string) {
    this.__PrimitivesSetter(this._key, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get value(): BOOLEAN {
    return this._value;
  }

  /**
   * The setter receives `boolean`
   **/
  public set value(v: boolean) {
    this.__PrimitivesSetter(this._value, v);
  }

  fromLiteral(data: IFloatLabelsEntry): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IFloatLabelsEntry {
    return super.__toLiteral() as IFloatLabelsEntry;
  }
}

Registry.register("furo.fat.Float.LabelsEntry", FloatLabelsEntry);
