// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { BOOLEAN, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface IUint64LabelsEntry
 */
export interface IUint64LabelsEntry {
  key?: string;
  value?: boolean;
}

/**
 * @interface TUint64LabelsEntry
 */
export interface TUint64LabelsEntry {
  key?: string;
  value?: boolean;
}

/**
 * Uint64LabelsEntry
 */
export class Uint64LabelsEntry extends FieldNode {
  /**
   **/
  private _key: STRING;

  /**
   **/
  private _value: BOOLEAN;

  public __defaultValues: IUint64LabelsEntry;

  constructor(initData?: IUint64LabelsEntry, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.fat.Uint64.LabelsEntry";
    this.__meta.description = "Uint64LabelsEntry";

    this.__meta.nodeFields = [
      {
        fieldName: "key",
        protoName: "key",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._key = new STRING(undefined, this, "key");

    /**
     **/
    this._value = new BOOLEAN(undefined, this, "value");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof Uint64LabelsEntry] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof Uint64LabelsEntry] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get key(): STRING {
    return this._key;
  }

  /**
   * The setter receives `string`
   **/
  public set key(v: string) {
    this.__PrimitivesSetter(this._key, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get value(): BOOLEAN {
    return this._value;
  }

  /**
   * The setter receives `boolean`
   **/
  public set value(v: boolean) {
    this.__PrimitivesSetter(this._value, v);
  }

  fromLiteral(data: IUint64LabelsEntry): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IUint64LabelsEntry {
    return super.__toLiteral() as IUint64LabelsEntry;
  }
}

Registry.register("furo.fat.Uint64.LabelsEntry", Uint64LabelsEntry);
