// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { BOOLEAN, FieldNode, RECURSION, Registry } from "@furo/open-models/dist/index";

import {
  SchemaOrReference as OpenapiV3SchemaOrReference,
  type ISchemaOrReference as IOpenapiV3SchemaOrReference,
  type TSchemaOrReference as TOpenapiV3SchemaOrReference,
} from "./SchemaOrReference";

/**
 * @interface IAdditionalPropertiesItem
 */
export interface IAdditionalPropertiesItem {
  schemaOrReference?: IOpenapiV3SchemaOrReference;
  boolean?: boolean;
}

/**
 * @interface TAdditionalPropertiesItem
 */
export interface TAdditionalPropertiesItem {
  schema_or_reference?: TOpenapiV3SchemaOrReference;
  boolean?: boolean;
}

/**
 * AdditionalPropertiesItem
 */
export class AdditionalPropertiesItem extends FieldNode {
  /**
   **/
  private _schemaOrReference: RECURSION<OpenapiV3SchemaOrReference, IOpenapiV3SchemaOrReference>;

  /**
   **/
  private _boolean: BOOLEAN;

  public __defaultValues: IAdditionalPropertiesItem;

  constructor(initData?: IAdditionalPropertiesItem, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.AdditionalPropertiesItem";
    this.__meta.description = "AdditionalPropertiesItem";

    this.__meta.nodeFields = [
      {
        fieldName: "schemaOrReference",
        protoName: "schema_or_reference",
        FieldConstructor: OpenapiV3SchemaOrReference,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
      {
        fieldName: "boolean",
        protoName: "boolean",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
    ];

    this.__meta.oneofGroups = new Map([["oneof", undefined]]);

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._schemaOrReference = new RECURSION<OpenapiV3SchemaOrReference, IOpenapiV3SchemaOrReference>(undefined, this, "schemaOrReference");

    /**
     **/
    this._boolean = new BOOLEAN(undefined, this, "boolean");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof AdditionalPropertiesItem] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof AdditionalPropertiesItem] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get schemaOrReference(): RECURSION<OpenapiV3SchemaOrReference, IOpenapiV3SchemaOrReference> {
    return this._schemaOrReference;
  }

  /**
   * The setter receives `IOpenapiV3SchemaOrReference`
   **/
  public set schemaOrReference(v: IOpenapiV3SchemaOrReference) {
    this.__TypeSetter(this._schemaOrReference, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get boolean(): BOOLEAN {
    return this._boolean;
  }

  /**
   * The setter receives `boolean`
   **/
  public set boolean(v: boolean) {
    this.__PrimitivesSetter(this._boolean, v);
  }

  fromLiteral(data: IAdditionalPropertiesItem): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IAdditionalPropertiesItem {
    return super.__toLiteral() as IAdditionalPropertiesItem;
  }
}

Registry.register("openapi.v3.AdditionalPropertiesItem", AdditionalPropertiesItem);
