// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry } from "@furo/open-models/dist/index";

import { Header as OpenapiV3Header, type IHeader as IOpenapiV3Header, type THeader as TOpenapiV3Header } from "./Header";
import { Reference as OpenapiV3Reference, type IReference as IOpenapiV3Reference, type TReference as TOpenapiV3Reference } from "./Reference";

/**
 * @interface IHeaderOrReference
 */
export interface IHeaderOrReference {
  header?: IOpenapiV3Header;
  reference?: IOpenapiV3Reference;
}

/**
 * @interface THeaderOrReference
 */
export interface THeaderOrReference {
  header?: TOpenapiV3Header;
  reference?: TOpenapiV3Reference;
}

/**
 * HeaderOrReference
 */
export class HeaderOrReference extends FieldNode {
  /**
   **/
  private _header: OpenapiV3Header;

  /**
   **/
  private _reference: OpenapiV3Reference;

  public __defaultValues: IHeaderOrReference;

  constructor(initData?: IHeaderOrReference, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.HeaderOrReference";
    this.__meta.description = "HeaderOrReference";

    this.__meta.nodeFields = [
      {
        fieldName: "header",
        protoName: "header",
        FieldConstructor: OpenapiV3Header,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
      {
        fieldName: "reference",
        protoName: "reference",
        FieldConstructor: OpenapiV3Reference,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
    ];

    this.__meta.oneofGroups = new Map([["oneof", undefined]]);

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._header = new OpenapiV3Header(undefined, this, "header");

    /**
     **/
    this._reference = new OpenapiV3Reference(undefined, this, "reference");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof HeaderOrReference] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof HeaderOrReference] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get header(): OpenapiV3Header {
    return this._header;
  }

  /**
   * The setter receives `IOpenapiV3Header | null`
   **/
  public set header(v: IOpenapiV3Header | null) {
    this.__TypeSetter(this._header, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get reference(): OpenapiV3Reference {
    return this._reference;
  }

  /**
   * The setter receives `IOpenapiV3Reference | null`
   **/
  public set reference(v: IOpenapiV3Reference | null) {
    this.__TypeSetter(this._reference, v);
  }

  fromLiteral(data: IHeaderOrReference): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IHeaderOrReference {
    return super.__toLiteral() as IHeaderOrReference;
  }
}

Registry.register("openapi.v3.HeaderOrReference", HeaderOrReference);
