// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import {
  RequestBodyOrReference as OpenapiV3RequestBodyOrReference,
  type IRequestBodyOrReference as IOpenapiV3RequestBodyOrReference,
  type TRequestBodyOrReference as TOpenapiV3RequestBodyOrReference,
} from "./RequestBodyOrReference";

/**
 * @interface INamedRequestBodyOrReference
 *  Automatically-generated message used to represent maps of RequestBodyOrReference as ordered (name,value) pairs.
 */
export interface INamedRequestBodyOrReference {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: IOpenapiV3RequestBodyOrReference;
}

/**
 * @interface TNamedRequestBodyOrReference
 *  Automatically-generated message used to represent maps of RequestBodyOrReference as ordered (name,value) pairs.
 */
export interface TNamedRequestBodyOrReference {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: TOpenapiV3RequestBodyOrReference;
}

/**
 * NamedRequestBodyOrReference
 *  Automatically-generated message used to represent maps of RequestBodyOrReference as ordered (name,value) pairs.
 */
export class NamedRequestBodyOrReference extends FieldNode {
  //  Map key
  private _name: STRING;

  //  Mapped value
  private _value: OpenapiV3RequestBodyOrReference;

  public __defaultValues: INamedRequestBodyOrReference;

  constructor(initData?: INamedRequestBodyOrReference, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.NamedRequestBodyOrReference";

    this.__meta.nodeFields = [
      {
        fieldName: "name",
        protoName: "name",
        FieldConstructor: STRING,
        constraints: {},
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: OpenapiV3RequestBodyOrReference,
        constraints: {},
      },
    ];

    // Initialize the fields
    //  Map key
    this._name = new STRING(undefined, this, "name");

    //  Mapped value
    this._value = new OpenapiV3RequestBodyOrReference(undefined, this, "value");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof NamedRequestBodyOrReference] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof NamedRequestBodyOrReference] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  //  Map key
  public get name(): STRING {
    return this._name;
  }

  public set name(v: string) {
    this.__PrimitivesSetter(this._name, v);
  }

  //  Mapped value
  public get value(): OpenapiV3RequestBodyOrReference {
    return this._value;
  }

  public set value(v: IOpenapiV3RequestBodyOrReference) {
    this.__TypeSetter(this._value, v);
  }

  fromLiteral(data: INamedRequestBodyOrReference) {
    super.__fromLiteral(data);
  }

  toLiteral(): INamedRequestBodyOrReference {
    return super.__toLiteral();
  }
}

Registry.register("openapi.v3.NamedRequestBodyOrReference", NamedRequestBodyOrReference);
