// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import {
  LinkOrReference as OpenapiV3LinkOrReference,
  type ILinkOrReference as IOpenapiV3LinkOrReference,
  type TLinkOrReference as TOpenapiV3LinkOrReference,
} from "./LinkOrReference";

/**
 * @interface INamedLinkOrReference
 *  Automatically-generated message used to represent maps of LinkOrReference as ordered (name,value) pairs.
 */
export interface INamedLinkOrReference {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: IOpenapiV3LinkOrReference;
}

/**
 * @interface TNamedLinkOrReference
 *  Automatically-generated message used to represent maps of LinkOrReference as ordered (name,value) pairs.
 */
export interface TNamedLinkOrReference {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: TOpenapiV3LinkOrReference;
}

/**
 * NamedLinkOrReference
 *  Automatically-generated message used to represent maps of LinkOrReference as ordered (name,value) pairs.
 */
export class NamedLinkOrReference extends FieldNode {
  /**
   * Map key
   **/
  private _name: STRING;

  /**
   * Mapped value
   **/
  private _value: OpenapiV3LinkOrReference;

  public __defaultValues: INamedLinkOrReference;

  constructor(initData?: INamedLinkOrReference, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.NamedLinkOrReference";
    this.__meta.description = "NamedLinkOrReference Automatically-generated message used to represent maps of LinkOrReference as ordered (name,value) pairs.";

    this.__meta.nodeFields = [
      {
        fieldName: "name",
        protoName: "name",
        FieldConstructor: STRING,
        constraints: {},
        description: "Map key",
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: OpenapiV3LinkOrReference,
        constraints: {},
        description: "Mapped value",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  Map key
     **/
    this._name = new STRING(undefined, this, "name");

    /**
     *  Mapped value
     **/
    this._value = new OpenapiV3LinkOrReference(undefined, this, "value");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof NamedLinkOrReference] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof NamedLinkOrReference] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Map key
   * The getter receives the FieldNode
   **/
  public get name(): STRING {
    return this._name;
  }

  /**
   * The setter receives `string`
   **/
  public set name(v: string) {
    this.__PrimitivesSetter(this._name, v);
  }

  /**
   *  Mapped value
   * The getter receives the FieldNode
   **/
  public get value(): OpenapiV3LinkOrReference {
    return this._value;
  }

  /**
   * The setter receives `IOpenapiV3LinkOrReference`
   **/
  public set value(v: IOpenapiV3LinkOrReference) {
    this.__TypeSetter(this._value, v);
  }

  fromLiteral(data: INamedLinkOrReference): void {
    super.__fromLiteral(data);
  }

  toLiteral(): INamedLinkOrReference {
    return super.__toLiteral() as INamedLinkOrReference;
  }
}

Registry.register("openapi.v3.NamedLinkOrReference", NamedLinkOrReference);
