// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import { XAny as OpenapiV3Any, type IXAny as IOpenapiV3Any, type TXAny as TOpenapiV3Any } from "./Any";

/**
 * @interface INamedAny
 *  Automatically-generated message used to represent maps of Any as ordered (name,value) pairs.
 */
export interface INamedAny {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: IOpenapiV3Any;
}

/**
 * @interface TNamedAny
 *  Automatically-generated message used to represent maps of Any as ordered (name,value) pairs.
 */
export interface TNamedAny {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: TOpenapiV3Any;
}

/**
 * NamedAny
 *  Automatically-generated message used to represent maps of Any as ordered (name,value) pairs.
 */
export class NamedAny extends FieldNode {
  /**
   * Map key
   **/
  private _name: STRING;

  /**
   * Mapped value
   **/
  private _value: OpenapiV3Any;

  public __defaultValues: INamedAny;

  constructor(initData?: INamedAny, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.NamedAny";
    this.__meta.description = "NamedAny Automatically-generated message used to represent maps of Any as ordered (name,value) pairs.";

    this.__meta.nodeFields = [
      {
        fieldName: "name",
        protoName: "name",
        FieldConstructor: STRING,
        constraints: {},
        description: "Map key",
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: OpenapiV3Any,
        constraints: {},
        description: "Mapped value",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  Map key
     **/
    this._name = new STRING(undefined, this, "name");

    /**
     *  Mapped value
     **/
    this._value = new OpenapiV3Any(undefined, this, "value");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof NamedAny] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof NamedAny] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Map key
   * The getter receives the FieldNode
   **/
  public get name(): STRING {
    return this._name;
  }

  /**
   * The setter receives `string`
   **/
  public set name(v: string) {
    this.__PrimitivesSetter(this._name, v);
  }

  /**
   *  Mapped value
   * The getter receives the FieldNode
   **/
  public get value(): OpenapiV3Any {
    return this._value;
  }

  /**
   * The setter receives `IOpenapiV3Any | null`
   **/
  public set value(v: IOpenapiV3Any | null) {
    this.__TypeSetter(this._value, v);
  }

  fromLiteral(data: INamedAny): void {
    super.__fromLiteral(data);
  }

  toLiteral(): INamedAny {
    return super.__toLiteral() as INamedAny;
  }
}

Registry.register("openapi.v3.NamedAny", NamedAny);
