// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import {
  HeaderOrReference as OpenapiV3HeaderOrReference,
  type IHeaderOrReference as IOpenapiV3HeaderOrReference,
  type THeaderOrReference as TOpenapiV3HeaderOrReference,
} from "./HeaderOrReference";

/**
 * @interface INamedHeaderOrReference
 *  Automatically-generated message used to represent maps of HeaderOrReference as ordered (name,value) pairs.
 */
export interface INamedHeaderOrReference {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: IOpenapiV3HeaderOrReference;
}

/**
 * @interface TNamedHeaderOrReference
 *  Automatically-generated message used to represent maps of HeaderOrReference as ordered (name,value) pairs.
 */
export interface TNamedHeaderOrReference {
  /**
   *  Map key
   */
  name?: string;
  /**
   *  Mapped value
   */
  value?: TOpenapiV3HeaderOrReference;
}

/**
 * NamedHeaderOrReference
 *  Automatically-generated message used to represent maps of HeaderOrReference as ordered (name,value) pairs.
 */
export class NamedHeaderOrReference extends FieldNode {
  //  Map key
  private _name: STRING;

  //  Mapped value
  private _value: OpenapiV3HeaderOrReference;

  public __defaultValues: INamedHeaderOrReference;

  constructor(initData?: INamedHeaderOrReference, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.NamedHeaderOrReference";

    this.__meta.nodeFields = [
      {
        fieldName: "name",
        protoName: "name",
        FieldConstructor: STRING,
        constraints: {},
      },
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: OpenapiV3HeaderOrReference,
        constraints: {},
      },
    ];

    // Initialize the fields
    //  Map key
    this._name = new STRING(undefined, this, "name");

    //  Mapped value
    this._value = new OpenapiV3HeaderOrReference(undefined, this, "value");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof NamedHeaderOrReference] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof NamedHeaderOrReference] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  //  Map key
  public get name(): STRING {
    return this._name;
  }

  public set name(v: string) {
    this.__PrimitivesSetter(this._name, v);
  }

  //  Mapped value
  public get value(): OpenapiV3HeaderOrReference {
    return this._value;
  }

  public set value(v: IOpenapiV3HeaderOrReference) {
    this.__TypeSetter(this._value, v);
  }

  fromLiteral(data: INamedHeaderOrReference) {
    super.__fromLiteral(data);
  }

  toLiteral(): INamedHeaderOrReference {
    return super.__toLiteral();
  }
}

Registry.register("openapi.v3.NamedHeaderOrReference", NamedHeaderOrReference);
