// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ARRAY, BOOLEAN, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import {
  CallbacksOrReferences as OpenapiV3CallbacksOrReferences,
  type ICallbacksOrReferences as IOpenapiV3CallbacksOrReferences,
  type TCallbacksOrReferences as TOpenapiV3CallbacksOrReferences,
} from "./CallbacksOrReferences";
import {
  ExternalDocs as OpenapiV3ExternalDocs,
  type IExternalDocs as IOpenapiV3ExternalDocs,
  type TExternalDocs as TOpenapiV3ExternalDocs,
} from "./ExternalDocs";
import { NamedAny as OpenapiV3NamedAny, type INamedAny as IOpenapiV3NamedAny, type TNamedAny as TOpenapiV3NamedAny } from "./NamedAny";
import {
  ParameterOrReference as OpenapiV3ParameterOrReference,
  type IParameterOrReference as IOpenapiV3ParameterOrReference,
  type TParameterOrReference as TOpenapiV3ParameterOrReference,
} from "./ParameterOrReference";
import {
  RequestBodyOrReference as OpenapiV3RequestBodyOrReference,
  type IRequestBodyOrReference as IOpenapiV3RequestBodyOrReference,
  type TRequestBodyOrReference as TOpenapiV3RequestBodyOrReference,
} from "./RequestBodyOrReference";
import { Responses as OpenapiV3Responses, type IResponses as IOpenapiV3Responses, type TResponses as TOpenapiV3Responses } from "./Responses";
import {
  SecurityRequirement as OpenapiV3SecurityRequirement,
  type ISecurityRequirement as IOpenapiV3SecurityRequirement,
  type TSecurityRequirement as TOpenapiV3SecurityRequirement,
} from "./SecurityRequirement";
import { Server as OpenapiV3Server, type IServer as IOpenapiV3Server, type TServer as TOpenapiV3Server } from "./Server";

/**
 * @interface IOperation
 *  Describes a single API operation on a path.
 */
export interface IOperation {
  tags?: string[];
  summary?: string;
  description?: string;
  externalDocs?: IOpenapiV3ExternalDocs;
  operationId?: string;
  parameters?: IOpenapiV3ParameterOrReference[];
  requestBody?: IOpenapiV3RequestBodyOrReference;
  responses?: IOpenapiV3Responses;
  callbacks?: IOpenapiV3CallbacksOrReferences;
  deprecated?: boolean;
  security?: IOpenapiV3SecurityRequirement[];
  servers?: IOpenapiV3Server[];
  specificationExtension?: IOpenapiV3NamedAny[];
}

/**
 * @interface TOperation
 *  Describes a single API operation on a path.
 */
export interface TOperation {
  tags?: string[];
  summary?: string;
  description?: string;
  external_docs?: TOpenapiV3ExternalDocs;
  operation_id?: string;
  parameters?: TOpenapiV3ParameterOrReference[];
  request_body?: TOpenapiV3RequestBodyOrReference;
  responses?: TOpenapiV3Responses;
  callbacks?: TOpenapiV3CallbacksOrReferences;
  deprecated?: boolean;
  security?: TOpenapiV3SecurityRequirement[];
  servers?: TOpenapiV3Server[];
  specification_extension?: TOpenapiV3NamedAny[];
}

/**
 * Operation
 *  Describes a single API operation on a path.
 */
export class Operation extends FieldNode {
  private _tags: ARRAY<STRING, string>;

  private _summary: STRING;

  private _description: STRING;

  private _externalDocs: OpenapiV3ExternalDocs;

  private _operationId: STRING;

  private _parameters: ARRAY<OpenapiV3ParameterOrReference, IOpenapiV3ParameterOrReference>;

  private _requestBody: OpenapiV3RequestBodyOrReference;

  private _responses: OpenapiV3Responses;

  private _callbacks: OpenapiV3CallbacksOrReferences;

  private _deprecated: BOOLEAN;

  private _security: ARRAY<OpenapiV3SecurityRequirement, IOpenapiV3SecurityRequirement>;

  private _servers: ARRAY<OpenapiV3Server, IOpenapiV3Server>;

  private _specificationExtension: ARRAY<OpenapiV3NamedAny, IOpenapiV3NamedAny>;

  public __defaultValues: IOperation;

  constructor(initData?: IOperation, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.Operation";

    this.__meta.nodeFields = [
      {
        fieldName: "tags",
        protoName: "tags",
        FieldConstructor: STRING,
        constraints: {},
      },
      {
        fieldName: "summary",
        protoName: "summary",
        FieldConstructor: STRING,
        constraints: {},
      },
      {
        fieldName: "description",
        protoName: "description",
        FieldConstructor: STRING,
        constraints: {},
      },
      {
        fieldName: "externalDocs",
        protoName: "external_docs",
        FieldConstructor: OpenapiV3ExternalDocs,
        constraints: {},
      },
      {
        fieldName: "operationId",
        protoName: "operation_id",
        FieldConstructor: STRING,
        constraints: {},
      },
      {
        fieldName: "parameters",
        protoName: "parameters",
        FieldConstructor: OpenapiV3ParameterOrReference,
        constraints: {},
      },
      {
        fieldName: "requestBody",
        protoName: "request_body",
        FieldConstructor: OpenapiV3RequestBodyOrReference,
        constraints: {},
      },
      {
        fieldName: "responses",
        protoName: "responses",
        FieldConstructor: OpenapiV3Responses,
        constraints: {},
      },
      {
        fieldName: "callbacks",
        protoName: "callbacks",
        FieldConstructor: OpenapiV3CallbacksOrReferences,
        constraints: {},
      },
      {
        fieldName: "deprecated",
        protoName: "deprecated",
        FieldConstructor: BOOLEAN,
        constraints: {},
      },
      {
        fieldName: "security",
        protoName: "security",
        FieldConstructor: OpenapiV3SecurityRequirement,
        constraints: {},
      },
      {
        fieldName: "servers",
        protoName: "servers",
        FieldConstructor: OpenapiV3Server,
        constraints: {},
      },
      {
        fieldName: "specificationExtension",
        protoName: "specification_extension",
        FieldConstructor: OpenapiV3NamedAny,
        constraints: {},
      },
    ];

    // Initialize the fields
    this._tags = new ARRAY<STRING, string>(undefined, this, "tags");

    this._summary = new STRING(undefined, this, "summary");

    this._description = new STRING(undefined, this, "description");

    this._externalDocs = new OpenapiV3ExternalDocs(undefined, this, "externalDocs");

    this._operationId = new STRING(undefined, this, "operationId");

    this._parameters = new ARRAY<OpenapiV3ParameterOrReference, IOpenapiV3ParameterOrReference>(undefined, this, "parameters");

    this._requestBody = new OpenapiV3RequestBodyOrReference(undefined, this, "requestBody");

    this._responses = new OpenapiV3Responses(undefined, this, "responses");

    this._callbacks = new OpenapiV3CallbacksOrReferences(undefined, this, "callbacks");

    this._deprecated = new BOOLEAN(undefined, this, "deprecated");

    this._security = new ARRAY<OpenapiV3SecurityRequirement, IOpenapiV3SecurityRequirement>(undefined, this, "security");

    this._servers = new ARRAY<OpenapiV3Server, IOpenapiV3Server>(undefined, this, "servers");

    this._specificationExtension = new ARRAY<OpenapiV3NamedAny, IOpenapiV3NamedAny>(undefined, this, "specificationExtension");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof Operation] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof Operation] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  public get tags(): ARRAY<STRING, string> {
    return this._tags;
  }

  public set tags(v: string[]) {
    this.__TypeSetter(this._tags, v);
  }

  public get summary(): STRING {
    return this._summary;
  }

  public set summary(v: string) {
    this.__PrimitivesSetter(this._summary, v);
  }

  public get description(): STRING {
    return this._description;
  }

  public set description(v: string) {
    this.__PrimitivesSetter(this._description, v);
  }

  public get externalDocs(): OpenapiV3ExternalDocs {
    return this._externalDocs;
  }

  public set externalDocs(v: IOpenapiV3ExternalDocs) {
    this.__TypeSetter(this._externalDocs, v);
  }

  public get operationId(): STRING {
    return this._operationId;
  }

  public set operationId(v: string) {
    this.__PrimitivesSetter(this._operationId, v);
  }

  public get parameters(): ARRAY<OpenapiV3ParameterOrReference, IOpenapiV3ParameterOrReference> {
    return this._parameters;
  }

  public set parameters(v: IOpenapiV3ParameterOrReference[]) {
    this.__TypeSetter(this._parameters, v);
  }

  public get requestBody(): OpenapiV3RequestBodyOrReference {
    return this._requestBody;
  }

  public set requestBody(v: IOpenapiV3RequestBodyOrReference) {
    this.__TypeSetter(this._requestBody, v);
  }

  public get responses(): OpenapiV3Responses {
    return this._responses;
  }

  public set responses(v: IOpenapiV3Responses) {
    this.__TypeSetter(this._responses, v);
  }

  public get callbacks(): OpenapiV3CallbacksOrReferences {
    return this._callbacks;
  }

  public set callbacks(v: IOpenapiV3CallbacksOrReferences) {
    this.__TypeSetter(this._callbacks, v);
  }

  public get deprecated(): BOOLEAN {
    return this._deprecated;
  }

  public set deprecated(v: boolean) {
    this.__PrimitivesSetter(this._deprecated, v);
  }

  public get security(): ARRAY<OpenapiV3SecurityRequirement, IOpenapiV3SecurityRequirement> {
    return this._security;
  }

  public set security(v: IOpenapiV3SecurityRequirement[]) {
    this.__TypeSetter(this._security, v);
  }

  public get servers(): ARRAY<OpenapiV3Server, IOpenapiV3Server> {
    return this._servers;
  }

  public set servers(v: IOpenapiV3Server[]) {
    this.__TypeSetter(this._servers, v);
  }

  public get specificationExtension(): ARRAY<OpenapiV3NamedAny, IOpenapiV3NamedAny> {
    return this._specificationExtension;
  }

  public set specificationExtension(v: IOpenapiV3NamedAny[]) {
    this.__TypeSetter(this._specificationExtension, v);
  }

  fromLiteral(data: IOperation) {
    super.__fromLiteral(data);
  }

  toLiteral(): IOperation {
    return super.__toLiteral();
  }
}

Registry.register("openapi.v3.Operation", Operation);
