// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry } from "@furo/open-models/dist/index";

import { Reference as OpenapiV3Reference, type IReference as IOpenapiV3Reference, type TReference as TOpenapiV3Reference } from "./Reference";
import { RequestBody as OpenapiV3RequestBody, type IRequestBody as IOpenapiV3RequestBody, type TRequestBody as TOpenapiV3RequestBody } from "./RequestBody";

/**
 * @interface IRequestBodyOrReference
 */
export interface IRequestBodyOrReference {
  requestBody?: IOpenapiV3RequestBody;
  reference?: IOpenapiV3Reference;
}

/**
 * @interface TRequestBodyOrReference
 */
export interface TRequestBodyOrReference {
  request_body?: TOpenapiV3RequestBody;
  reference?: TOpenapiV3Reference;
}

/**
 * RequestBodyOrReference
 */
export class RequestBodyOrReference extends FieldNode {
  /**
   **/
  private _requestBody: OpenapiV3RequestBody;

  /**
   **/
  private _reference: OpenapiV3Reference;

  public __defaultValues: IRequestBodyOrReference;

  constructor(initData?: IRequestBodyOrReference, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.RequestBodyOrReference";
    this.__meta.description = "RequestBodyOrReference";

    this.__meta.nodeFields = [
      {
        fieldName: "requestBody",
        protoName: "request_body",
        FieldConstructor: OpenapiV3RequestBody,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
      {
        fieldName: "reference",
        protoName: "reference",
        FieldConstructor: OpenapiV3Reference,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
    ];

    this.__meta.oneofGroups = new Map([["oneof", undefined]]);

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._requestBody = new OpenapiV3RequestBody(undefined, this, "requestBody");

    /**
     **/
    this._reference = new OpenapiV3Reference(undefined, this, "reference");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof RequestBodyOrReference] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof RequestBodyOrReference] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get requestBody(): OpenapiV3RequestBody {
    return this._requestBody;
  }

  /**
   * The setter receives `IOpenapiV3RequestBody | null`
   **/
  public set requestBody(v: IOpenapiV3RequestBody | null) {
    this.__TypeSetter(this._requestBody, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get reference(): OpenapiV3Reference {
    return this._reference;
  }

  /**
   * The setter receives `IOpenapiV3Reference | null`
   **/
  public set reference(v: IOpenapiV3Reference | null) {
    this.__TypeSetter(this._reference, v);
  }

  fromLiteral(data: IRequestBodyOrReference): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IRequestBodyOrReference {
    return super.__toLiteral() as IRequestBodyOrReference;
  }
}

Registry.register("openapi.v3.RequestBodyOrReference", RequestBodyOrReference);
