// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ARRAY, BOOLEAN, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import { MediaTypes as OpenapiV3MediaTypes, type IMediaTypes as IOpenapiV3MediaTypes, type TMediaTypes as TOpenapiV3MediaTypes } from "./MediaTypes";
import { NamedAny as OpenapiV3NamedAny, type INamedAny as IOpenapiV3NamedAny, type TNamedAny as TOpenapiV3NamedAny } from "./NamedAny";

/**
 * @interface IRequestBody
 *  Describes a single request body.
 */
export interface IRequestBody {
  description?: string;
  content?: IOpenapiV3MediaTypes;
  required?: boolean;
  specificationExtension?: IOpenapiV3NamedAny[];
}

/**
 * @interface TRequestBody
 *  Describes a single request body.
 */
export interface TRequestBody {
  description?: string;
  content?: TOpenapiV3MediaTypes;
  required?: boolean;
  specification_extension?: TOpenapiV3NamedAny[];
}

/**
 * RequestBody
 *  Describes a single request body.
 */
export class RequestBody extends FieldNode {
  /**
   **/
  private _description: STRING;

  /**
   **/
  private _content: OpenapiV3MediaTypes;

  /**
   **/
  private _required: BOOLEAN;

  /**
   **/
  private _specificationExtension: ARRAY<OpenapiV3NamedAny, IOpenapiV3NamedAny>;

  public __defaultValues: IRequestBody;

  constructor(initData?: IRequestBody, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.RequestBody";
    this.__meta.description = "RequestBody Describes a single request body.";

    this.__meta.nodeFields = [
      {
        fieldName: "description",
        protoName: "description",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
      },
      {
        fieldName: "content",
        protoName: "content",
        FieldConstructor: OpenapiV3MediaTypes,
        constraints: {},
        description: "",
      },
      {
        fieldName: "required",
        protoName: "required",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "",
      },
      {
        fieldName: "specificationExtension",
        protoName: "specification_extension",
        FieldConstructor: OpenapiV3NamedAny,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._description = new STRING(undefined, this, "description");

    /**
     **/
    this._content = new OpenapiV3MediaTypes(undefined, this, "content");

    /**
     **/
    this._required = new BOOLEAN(undefined, this, "required");

    /**
     **/
    this._specificationExtension = new ARRAY<OpenapiV3NamedAny, IOpenapiV3NamedAny>(undefined, this, "specificationExtension");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof RequestBody] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof RequestBody] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get description(): STRING {
    return this._description;
  }

  /**
   * The setter receives `string`
   **/
  public set description(v: string) {
    this.__PrimitivesSetter(this._description, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get content(): OpenapiV3MediaTypes {
    return this._content;
  }

  /**
   * The setter receives `IOpenapiV3MediaTypes`
   **/
  public set content(v: IOpenapiV3MediaTypes) {
    this.__TypeSetter(this._content, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get required(): BOOLEAN {
    return this._required;
  }

  /**
   * The setter receives `boolean`
   **/
  public set required(v: boolean) {
    this.__PrimitivesSetter(this._required, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get specificationExtension(): ARRAY<OpenapiV3NamedAny, IOpenapiV3NamedAny> {
    return this._specificationExtension;
  }

  /**
   * The setter receives `IOpenapiV3NamedAny[]`
   **/
  public set specificationExtension(v: IOpenapiV3NamedAny[]) {
    this.__TypeSetter(this._specificationExtension, v);
  }

  fromLiteral(data: IRequestBody): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IRequestBody {
    return super.__toLiteral() as IRequestBody;
  }
}

Registry.register("openapi.v3.RequestBody", RequestBody);
