// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry } from "@furo/open-models/dist/index";

import { Reference as OpenapiV3Reference, type IReference as IOpenapiV3Reference, type TReference as TOpenapiV3Reference } from "./Reference";
import { Response as OpenapiV3Response, type IResponse as IOpenapiV3Response, type TResponse as TOpenapiV3Response } from "./Response";

/**
 * @interface IResponseOrReference
 */
export interface IResponseOrReference {
  response?: IOpenapiV3Response;
  reference?: IOpenapiV3Reference;
}

/**
 * @interface TResponseOrReference
 */
export interface TResponseOrReference {
  response?: TOpenapiV3Response;
  reference?: TOpenapiV3Reference;
}

/**
 * ResponseOrReference
 */
export class ResponseOrReference extends FieldNode {
  /**
   **/
  private _response: OpenapiV3Response;

  /**
   **/
  private _reference: OpenapiV3Reference;

  public __defaultValues: IResponseOrReference;

  constructor(initData?: IResponseOrReference, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "openapi.v3.ResponseOrReference";
    this.__meta.description = "ResponseOrReference";

    this.__meta.nodeFields = [
      {
        fieldName: "response",
        protoName: "response",
        FieldConstructor: OpenapiV3Response,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
      {
        fieldName: "reference",
        protoName: "reference",
        FieldConstructor: OpenapiV3Reference,
        constraints: {},
        description: "",
        oneofGroup: "oneof",
      },
    ];

    this.__meta.oneofGroups = new Map([["oneof", undefined]]);

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._response = new OpenapiV3Response(undefined, this, "response");

    /**
     **/
    this._reference = new OpenapiV3Reference(undefined, this, "reference");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof ResponseOrReference] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof ResponseOrReference] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get response(): OpenapiV3Response {
    return this._response;
  }

  /**
   * The setter receives `IOpenapiV3Response`
   **/
  public set response(v: IOpenapiV3Response) {
    this.__TypeSetter(this._response, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get reference(): OpenapiV3Reference {
    return this._reference;
  }

  /**
   * The setter receives `IOpenapiV3Reference`
   **/
  public set reference(v: IOpenapiV3Reference) {
    this.__TypeSetter(this._reference, v);
  }

  fromLiteral(data: IResponseOrReference): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IResponseOrReference {
    return super.__toLiteral() as IResponseOrReference;
  }
}

Registry.register("openapi.v3.ResponseOrReference", ResponseOrReference);
