const enums = new Set([
  "@ui5/webcomponents/dist/types/SelectTextSeparator.js",
  "@ui5/webcomponents/dist/types/InputSuggestionsFilter.js",
  "@ui5/webcomponents/dist/types/AvatarColorScheme.js",
  "@ui5/webcomponents/dist/types/AvatarMode.js",
  "@ui5/webcomponents/dist/types/AvatarSize.js",
  "@furo/ui5/dist/types/ValueState.js",
  "@furo/ui5/dist/types/AvatarSize.js",
  "@furo/ui5/dist/types/AvatarGroupType.js",
  "@ui5/webcomponents/dist/types/BusyIndicatorSize.js",
  "@ui5/webcomponents-base/dist/types/CalendarType.js",
  "@ui5/webcomponents/dist/types/BusyIndicatorTextPlacement.js",
  "@ui5/webcomponents/dist/types/ButtonAccessibleRole.js",
  "@ui5/webcomponents/dist/types/ButtonDesign.js",
  "@ui5/webcomponents/dist/types/ButtonType.js",
  "@ui5/webcomponents/dist/types/AvatarShape.js",
  "@ui5/webcomponents/dist/types/ComboBoxFilter.js",
  "@ui5/webcomponents-base/dist/types/ValueState.js",
  "@ui5/webcomponents/dist/types/WrappingType.js",
  "@ui5/webcomponents/dist/types/HighlightTypes.js",
  "@ui5/webcomponents/dist/types/ListItemType.js",
  "@ui5/webcomponents/dist/types/BadgeDesign.js",
  "@ui5/webcomponents/dist/types/BreadcrumbsSeparatorStyle.js",
  "@ui5/webcomponents/dist/types/AvatarGroupType.js",
  "@ui5/webcomponents-fiori/dist/types/BarDesign.js",
  "@ui5/webcomponents/dist/types/BreadcrumbsDesign.js",
  "@ui5/webcomponents/dist/types/CalendarSelectionMode.js",
  "@ui5/webcomponents/dist/types/CarouselArrowsPlacement.js",
  "@ui5/webcomponents/dist/types/BackgroundDesign.js",
  "@ui5/webcomponents/dist/types/BorderDesign.js",
  "@ui5/webcomponents/dist/types/PopupAccessibleRole.js",
  "@ui5/webcomponents/dist/types/CarouselPageIndicatorStyle.js",
  "@furo/ui5/dist/types/ActicoViolationDisplay.js",
  "@ui5/webcomponents-fiori/dist/types/SideContentFallDown.js",
  "@ui5/webcomponents-fiori/dist/types/SideContentPosition.js",
  "@ui5/webcomponents-fiori/dist/types/SideContentVisibility.js",
  "@furo/ui5/dist/types/DisplayDateTimeType.js",
  "@furo/ui5/dist/types/AutoState.js",
  "@furo/ui5/dist/types/DisplayNumberType.js",
  "@furo/ui5/dist/types/IconShape.js",
  "@furo/ui5/dist/types/IconSize.js",
  "@ui5/webcomponents-fiori/dist/types/FCLLayout.js",
  "@furo/ui5/dist/types/FormFieldSegmentationPatterns.js",
  "@ui5/webcomponents/dist/types/IconDesign.js",
  "@ui5/webcomponents-fiori/dist/types/IllustrationMessageSize.js",
  "@ui5/webcomponents/dist/types/TitleLevel.js",
  "@ui5/webcomponents/dist/types/InputType.js",
  "@furo/ui5/dist/types/BackgroundDesign.js",
  "@ui5/webcomponents/dist/types/LinkDesign.js",
  "@ui5/webcomponents/dist/types/ListGrowingMode.js",
  "@ui5/webcomponents/dist/types/ListMode.js",
  "@ui5/webcomponents/dist/types/ListSeparators.js",
  "@ui5/webcomponents-fiori/dist/types/MediaGalleryLayout.js",
  "@ui5/webcomponents-fiori/dist/types/MediaGalleryMenuHorizontalAlign.js",
  "@ui5/webcomponents-fiori/dist/types/MediaGalleryMenuVerticalAlign.js",
  "@ui5/webcomponents-fiori/dist/types/MediaGalleryItemLayout.js",
  "@ui5/webcomponents/dist/types/MessageStripDesign.js",
  "@ui5/webcomponents/dist/types/Priority.js",
  "@ui5/webcomponents-fiori/dist/types/PageBackgroundDesign.js",
  "@ui5/webcomponents/dist/types/PanelAccessibleRole.js",
  "@ui5/webcomponents/dist/types/PopoverHorizontalAlign.js",
  "@ui5/webcomponents/dist/types/PopoverPlacementType.js",
  "@ui5/webcomponents/dist/types/PopoverVerticalAlign.js",
  "@furo/ui5/dist/types/ResponsiveLayoutSize.js",
  "@furo/ui5/dist/types/SidepanelState.js",
  "@ui5/webcomponents/dist/types/SwitchDesign.js",
  "@ui5/webcomponents/dist/types/SemanticColor.js",
  "@ui5/webcomponents/dist/types/TabContainerBackgroundDesign.js",
  "@ui5/webcomponents/dist/types/TabLayout.js",
  "@ui5/webcomponents/dist/types/Highlight.js",
  "@ui5/webcomponents/dist/types/TabsOverflowMode.js",
  "@ui5/webcomponents/dist/types/OverflowMode.js",
  "@ui5/webcomponents/dist/types/TableGrowingMode.js",
  "@ui5/webcomponents/dist/types/TableMode.js",
  "@ui5/webcomponents/dist/types/TableColumnPopinDisplay.js",
  "@ui5/webcomponents/dist/types/TableRowType.js",
  "@ui5/webcomponents-fiori/dist/types/WizardContentLayout.js",
  "@ui5/webcomponents-fiori/dist/types/TimelineLayout.js",
  "@ui5/webcomponents/dist/types/ToastPlacement.js",
  "@ui5/webcomponents/dist/types/ToolbarAlign.js",
  "@ui5/webcomponents/dist/types/ToolbarItemOverflowBehavior.js",
  "@furo/ui5/dist/types/TreeTableMode.js",
  "@ui5/webcomponents-fiori/dist/types/UploadState.js",
  "@ui5/webcomponents/dist/types/SegmentedButtonMode.js",
  "@furo/ui5/dist/SidepanelContainer.js",
  "@furo/ui5/dist/Sidepanel.js",
  "@furo/ui5/dist/CustomListItem.js",
  "@furo/ui5/dist/SidepanelIcon.js",
  "@furo/ui5/dist/SidepanelIcon.js",

  "@ui5/webcomponents/dist/types/BarDesign.js",
  "@ui5/webcomponents/dist/types/BreadcrumbsSeparator.js",
  "@ui5/webcomponents/dist/types/ButtonBadgeDesign.js",
  "@ui5/webcomponents/dist/types/CalendarWeekNumbering.js",
  "@ui5/webcomponents/dist/types/CalendarLegendItemType.js",
  "@ui5/webcomponents/dist/types/CarouselPageIndicatorType.js",
  "@ui5/webcomponents/dist/types/CalendarWeekNumbering.js",
  "@ui5/webcomponents/dist/types/CalendarWeekNumbering.js",
  "@ui5/webcomponents/dist/types/CalendarWeekNumbering.js",
  "@ui5/webcomponents/dist/types/ExpandableTextOverflowMode.js",
  "@ui5/webcomponents/dist/types/TextEmptyIndicatorMode.js",
  "@ui5/webcomponents/dist/types/IconMode.js",
  "@ui5/webcomponents/dist/types/InteractiveAreaSize.js",
  "@ui5/webcomponents/dist/types/LinkAccessibleRole.js",
  "@ui5/webcomponents/dist/types/ListSelectionMode.js",
  "@ui5/webcomponents/dist/types/ListSeparator.js",
  "@ui5/webcomponents/dist/types/ListAccessibleRole.js",
  "@ui5/webcomponents/dist/types/NotificationListGrowingMode.js",
  "@ui5/webcomponents-fiori/dist/types/NotificationListItemImportance.js",
  "@ui5/webcomponents/dist/types/PopoverPlacement.js",
  "@ui5/webcomponents/dist/types/RatingIndicatorSize.js",
  "@ui5/webcomponents/dist/types/PopoverPlacement.js",
  "@ui5/webcomponents/dist/types/SegmentedButtonSelectionMode.js",
  "@ui5/webcomponents-fiori/dist/types/SideNavigationItemDesign.js",
  "@ui5/webcomponents-fiori/dist/types/SideNavigationItemDesign.js",
  "@ui5/webcomponents-fiori/dist/SideNavigationSelectableItemBase.js",
  "@ui5/webcomponents/dist/types/CalendarLegendItemType.js",
  "@ui5/webcomponents-compat/dist/types/TableGrowingMode.js",
  "@ui5/webcomponents-compat/dist/types/TableMode.js",
  "@ui5/webcomponents-compat/dist/types/TableColumnPopinDisplay.js",
  "@ui5/webcomponents-compat/dist/types/TableRowType.js",
  "@ui5/webcomponents/dist/types/TagDesign.js",
  "@ui5/webcomponents/dist/types/TagSize.js",
  "@ui5/webcomponents/dist/types/TextEmptyIndicatorMode.js",
  "@ui5/webcomponents-fiori/dist/types/TimelineGrowingMode.js",
  "@ui5/webcomponents/dist/types/ToolbarDesign.js",
  "@ui5/webcomponents/dist/types/ListSelectionMode.js",
  "@ui5/webcomponents-fiori/dist/types/UploadCollectionSelectionMode.js",
  "@ui5/webcomponents-fiori/dist/types/IllustrationMessageDesign.js",
  "@furo/ui5/dist/types/FlexibleGridSetting.js",
  "@ui5/webcomponents/dist/types/BarAccessibleRole.js",
]);

export function isRegistredEnumType(type, references) {
  if (references != null && references?.length > 0) {
    // find name in references
    const ref = references.find((reference) => reference.name === type.split(' | ')[0]);
    if (ref) {
      if (enums.has(`${ref.package}/${ref.module}`)) {
        return true;
      } else {
          console.log(`${ref.package}/${ref.module}`);
        return false;
      }
    } else {
      return false;
    }
  }
  return false;
}
