// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, INT32, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface IXDate
 *  Represents a whole calendar date, e.g. date of birth. The time of day and
 *   time zone are either specified elsewhere or are not significant. The date
 *   is relative to the Proleptic Gregorian Calendar. The day may be 0 to
 *   represent a year and month where the day is not significant, e.g. credit card
 *   expiration date. The year may be 0 to represent a month and day independent
 *   of year, e.g. anniversary date. Related types are [google.type.TimeOfDay][google.type.TimeOfDay]
 *   and `google.protobuf.Timestamp`.
 */
export interface IXDate {
  /**
   *  Year of date. Must be from 1 to 9999, or 0 if specifying a date without
   *   a year.
   */
  year?: number;
  /**
   *  Month of year. Must be from 1 to 12.
   */
  month?: number;
  /**
   *  Day of month. Must be from 1 to 31 and valid for the year and month, or 0
   *   if specifying a year/month where the day is not significant.
   */
  day?: number;
  /**
   *  String representation of the reference
   */
  displayName?: string;
}

/**
 * @interface TXDate
 *  Represents a whole calendar date, e.g. date of birth. The time of day and
 *   time zone are either specified elsewhere or are not significant. The date
 *   is relative to the Proleptic Gregorian Calendar. The day may be 0 to
 *   represent a year and month where the day is not significant, e.g. credit card
 *   expiration date. The year may be 0 to represent a month and day independent
 *   of year, e.g. anniversary date. Related types are [google.type.TimeOfDay][google.type.TimeOfDay]
 *   and `google.protobuf.Timestamp`.
 */
export interface TXDate {
  /**
   *  Year of date. Must be from 1 to 9999, or 0 if specifying a date without
   *   a year.
   */
  year?: number;
  /**
   *  Month of year. Must be from 1 to 12.
   */
  month?: number;
  /**
   *  Day of month. Must be from 1 to 31 and valid for the year and month, or 0
   *   if specifying a year/month where the day is not significant.
   */
  day?: number;
  /**
   *  String representation of the reference
   */
  display_name?: string;
}

/**
 * XDate
 *  Represents a whole calendar date, e.g. date of birth. The time of day and
 *   time zone are either specified elsewhere or are not significant. The date
 *   is relative to the Proleptic Gregorian Calendar. The day may be 0 to
 *   represent a year and month where the day is not significant, e.g. credit card
 *   expiration date. The year may be 0 to represent a month and day independent
 *   of year, e.g. anniversary date. Related types are [google.type.TimeOfDay][google.type.TimeOfDay]
 *   and `google.protobuf.Timestamp`.
 */
export class XDate extends FieldNode {
  /**
   * Year of date. Must be from 1 to 9999, or 0 if specifying a date without
   *  a year.
   **/
  private _year: INT32;

  /**
   * Month of year. Must be from 1 to 12.
   **/
  private _month: INT32;

  /**
   * Day of month. Must be from 1 to 31 and valid for the year and month, or 0
   *  if specifying a year/month where the day is not significant.
   **/
  private _day: INT32;

  /**
   * String representation of the reference
   **/
  private _displayName: STRING;

  public __defaultValues: IXDate;

  constructor(initData?: IXDate, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.type.Date";
    this.__meta.description =
      "XDate Represents a whole calendar date, e.g. date of birth. The time of day and\n  time zone are either specified elsewhere or are not significant. The date\n  is relative to the Proleptic Gregorian Calendar. The day may be 0 to\n  represent a year and month where the day is not significant, e.g. credit card\n  expiration date. The year may be 0 to represent a month and day independent\n  of year, e.g. anniversary date. Related types are [google.type.TimeOfDay][google.type.TimeOfDay]\n  and `google.protobuf.Timestamp`.";

    this.__meta.nodeFields = [
      {
        fieldName: "year",
        protoName: "year",
        FieldConstructor: INT32,
        constraints: {},
        description: "Year of date. Must be from 1 to 9999, or 0 if specifying a date without\n  a year.",
      },
      {
        fieldName: "month",
        protoName: "month",
        FieldConstructor: INT32,
        constraints: {},
        description: "Month of year. Must be from 1 to 12.",
      },
      {
        fieldName: "day",
        protoName: "day",
        FieldConstructor: INT32,
        constraints: {},
        description:
          "Day of month. Must be from 1 to 31 and valid for the year and month, or 0\n  if specifying a year/month where the day is not significant.",
      },
      {
        fieldName: "displayName",
        protoName: "display_name",
        FieldConstructor: STRING,
        constraints: {},
        description: "String representation of the reference",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  Year of date. Must be from 1 to 9999, or 0 if specifying a date without
     *   a year.
     **/
    this._year = new INT32(undefined, this, "year");

    /**
     *  Month of year. Must be from 1 to 12.
     **/
    this._month = new INT32(undefined, this, "month");

    /**
     *  Day of month. Must be from 1 to 31 and valid for the year and month, or 0
     *   if specifying a year/month where the day is not significant.
     **/
    this._day = new INT32(undefined, this, "day");

    /**
     *  String representation of the reference
     **/
    this._displayName = new STRING(undefined, this, "displayName");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof XDate] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof XDate] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Year of date. Must be from 1 to 9999, or 0 if specifying a date without
   *   a year.
   * The getter receives the FieldNode
   **/
  public get year(): INT32 {
    return this._year;
  }

  /**
   * The setter receives `number`
   **/
  public set year(v: number) {
    this.__PrimitivesSetter(this._year, v);
  }

  /**
   *  Month of year. Must be from 1 to 12.
   * The getter receives the FieldNode
   **/
  public get month(): INT32 {
    return this._month;
  }

  /**
   * The setter receives `number`
   **/
  public set month(v: number) {
    this.__PrimitivesSetter(this._month, v);
  }

  /**
   *  Day of month. Must be from 1 to 31 and valid for the year and month, or 0
   *   if specifying a year/month where the day is not significant.
   * The getter receives the FieldNode
   **/
  public get day(): INT32 {
    return this._day;
  }

  /**
   * The setter receives `number`
   **/
  public set day(v: number) {
    this.__PrimitivesSetter(this._day, v);
  }

  /**
   *  String representation of the reference
   * The getter receives the FieldNode
   **/
  public get displayName(): STRING {
    return this._displayName;
  }

  /**
   * The setter receives `string`
   **/
  public set displayName(v: string) {
    this.__PrimitivesSetter(this._displayName, v);
  }

  fromLiteral(data: IXDate): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IXDate {
    return super.__toLiteral() as IXDate;
  }
}

Registry.register("furo.type.Date", XDate);
