// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type { ListItemBaseClickEventDetail } from "@ui5/webcomponents/dist/ListItemBase.js";
import * as React from "react";

export interface CbItemCustom extends React.HTMLAttributes<HTMLElement> {
  onclick?: (d: CustomEvent<ListItemBaseClickEventDetail>) => void;
  // properties

  // attributes

  /**
   * Defines the text of the component.
   * Used for filtering, autocomplete, and mobile rendering.
   */
  text?: string | undefined;

  /**
   * Defines the value of the component.
   * Used for programmatic selection via the `selectedValue` property.
   */
  value?: string | undefined;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * A combobox item whose content comes from the default slot instead of the `text` property.
       *
       * ```html
       * <furo-ui5-combobox placeholder="Pick a city">
       * <furo-ui5-cb-item-custom text="Zurich">
       * <div style="display:flex;gap:.5rem;align-items:center">
       * <furo-ui5-icon name="building"></furo-ui5-icon><span>Zurich</span>
       * </div>
       * </furo-ui5-cb-item-custom>
       * </furo-ui5-combobox>
       * ```
       *
       * This is a pass-through wrapper around `furo-ui5-cb-item-custom`: the UI5 API (properties, events,
       * slots) is inherited unchanged and no data binding is added.
       *
       * The `furo-ui5-cb-item-custom` is a combobox item component
       * that allows placing custom content inside a combobox item.
       * The `text` property is used for filtering and auto-complete.
       * For highlighting functionality, see `@ui5/webcomponents-base/dist/util/generateHighlightedMarkup.js`.
       *
       * The `furo-ui5-cb-item-custom` is a combobox item component
       * that allows placing custom content inside a combobox item.
       * The `text` property is used for filtering and auto-complete.
       * For highlighting functionality, see `@ui5/webcomponents-base/dist/util/generateHighlightedMarkup.js`.
       *
       * A class to serve as a foundation
       * for the `ListItem` and `ListItemGroupHeader` classes.
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-cb-item-custom": CbItemCustom;
    }
  }
}
