// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import * as React from "react";

export interface CellFloat extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties
  // attributes
  // no attributes defined.
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * `cell-float`
       * The cell-float component displays a FieldNode of type `float` in read only mode.
       *
       * The component uses locale from the environment to display the value accordingly.
       * https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
       *
       * Every cell-xxx component should implement the following API:
       * - function: bindData(fieldNode){...}
       */
      "cell-float": CellFloat;
    }
  }
}
