// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import * as React from "react";

export interface CellGoogleTypeDate extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties
  // attributes
  // no attributes defined.
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * `cell-google-type-date`
       * The cell-google-type-date component displays a FieldNode of type `google.type.Date` in read only mode.
       *
       * The component uses locale from the environment to display the date value accordingly.
       * https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/format
       *
       * Every cell-xxx component should implement the following API:
       * - function: bindData(fieldNode){...}
       */
      "cell-google-type-date": CellGoogleTypeDate;
    }
  }
}
