// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import * as React from "react";

export interface CellGoogleTypeTimeofday extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties
  // attributes
  // no attributes defined.
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * `cell-google-type-timeofday`
       * The cell-google-type-timeofday component displays a FieldNode of type `google.type.TimeOfDay` in read only mode.
       *
       * The component uses locale from the environment to display the time value accordingly.
       * https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString
       *
       * Every cell-xxx component should implement the following API:
       * - function: bindData(fieldNode){...}
       */
      "cell-google-type-timeofday": CellGoogleTypeTimeofday;
    }
  }
}
