// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import * as React from "react";

export interface CellString extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties
  // attributes
  // no attributes defined.
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * `cell-string`
       * The cell-string component displays a FieldNode of type `string` in read only mode.
       *
       * Every cell-xxx component should implement the following API:
       * - function: bindData(fieldNode){...}
       */
      "cell-string": CellString;
    }
  }
}
