// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type { STRING, StringValue } from "@furo/open-models/";
import * as React from "react";

import type { FuroFatString } from "@/models/index.js";

export interface ColorPicker extends React.HTMLAttributes<HTMLElement> {
  onchange?: (d: CustomEvent) => void;
  // properties

  /**
   * Use this to bind a model field by attribute.
   */
  model?: STRING | FuroFatString | StringValue;

  // attributes

  /**
   * Defines the accessible name of the component.
   */
  accessibleName?: string | undefined;

  /**
   * Receives id(or many ids) of the elements that label the component.
   */
  accessibleNameRef?: string | undefined;

  /**
   * Determines the name by which the component will be identified upon submission in an HTML form.
   *
   * **Note:** This property is only applicable within the context of an HTML Form element.
   */
  name?: string | undefined;

  /**
   * When set to `true`, the alpha slider and inputs for RGB values will not be displayed.
   */
  simplified?: boolean;

  /**
   * Defines the currently selected color of the component.
   *
   * **Note**: use HEX, RGB, RGBA, HSV formats or a CSS color name when modifying this property.
   */
  value?: string;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The 'furo-ui5-color-picker' component lets the user select a color, with data binding.
       *
       * It supports all features from the [SAP ui5 ColorPicker element](https://ui5.github.io/webcomponents/components/ColorPicker/).
       *
       * The selected color is a plain `string` (HEX, RGB, RGBA, HSV or a CSS color name). You can bind any
       * `string` type: `primitives.STRING`, the `furo.fat.String` type or the `google.protobuf.StringValue` type.
       *
       * ```html
       * <furo-ui5-color-picker .model="${fieldNode}"></furo-ui5-color-picker>
       * ```
       *
       * ### Overview
       * The `furo-ui5-color-picker` allows users to choose any color and provides different input options for selecting colors.
       *
       * ### Usage
       *
       * #### When to use
       * Use the color picker if:
       *
       * -  users need to select any color freely.
       *
       * #### When not to use
       *
       * -  Users need to select one color from a predefined set of colors. Use the ColorPalette component instead.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/ColorPicker.js";`
       *
       * ### Overview
       * The `furo-ui5-color-picker` allows users to choose any color and provides different input options for selecting colors.
       *
       * ### Usage
       *
       * #### When to use
       * Use the color picker if:
       *
       * -  users need to select any color freely.
       *
       * #### When not to use
       *
       * -  Users need to select one color from a predefined set of colors. Use the ColorPalette component instead.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/ColorPicker.js";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-color-picker": ColorPicker;
    }
  }
}
