// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import * as React from "react";

export interface DisplayFuroTypeMoney extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties
  // attributes
  // no attributes defined.
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * `display-furo-type-money`
       * The display-furo-type-money component displays a FieldNode of type `furo.type.Money` in read only mode.
       *
       * If the field `display_name` is set, the component uses that value for the display, otherwise it
       * formats the amount as a currency according to the environment locale.
       * https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
       *
       * Every display-xxx component should implement the following API:
       * - function: bindData(fieldNode){...}
       */
      "display-furo-type-money": DisplayFuroTypeMoney;
    }
  }
}
