// DO NOT EDIT this file was generated with scripts/IntrinsicElements

import type {
  FCLAccessibilityAttributes,
  FlexibleColumnLayoutColumnLayout,
  FlexibleColumnLayoutLayoutChangeEventDetail,
  FlexibleColumnLayoutLayoutConfigurationChangeEventDetail,
  LayoutConfiguration,
} from "@ui5/webcomponents-fiori/dist/FlexibleColumnLayout.js";
import type FCLLayout from "@ui5/webcomponents-fiori/dist/types/FCLLayout.js";
import * as React from "react";

export interface FlexibleColumnLayout extends React.HTMLAttributes<HTMLElement> {
  "onlayout-change"?: (d: CustomEvent<FlexibleColumnLayoutLayoutChangeEventDetail>) => void;
  "onlayout-configuration-change"?: (d: CustomEvent<FlexibleColumnLayoutLayoutConfigurationChangeEventDetail>) => void;
  // properties

  // attributes

  /**
   * Defines additional accessibility attributes on different areas of the component.
   *
   * The accessibilityAttributes object has the following fields,
   * where each field is an object supporting one or more accessibility attributes:
   *
   * - **startColumn**: `startColumn.role` and `startColumn.name`.
   * - **midColumn**: `midColumn.role` and `midColumn.name`.
   * - **endColumn**: `endColumn.role` and `endColumn.name`.
   * - **startSeparator**: `startSeparator.role` and `startSeparator.name`.
   * - **endSeparator**: `endSeparator.role` and `endSeparator.name`.
   *
   * The accessibility attributes support the following values:
   *
   * - **role**: Defines the accessible ARIA landmark role of the area.
   * Accepts the following values: `none`, `complementary`, `contentinfo`, `main` or `region`.
   *
   * - **name**: Defines the accessible ARIA name of the area.
   * Accepts any string.
   */
  accessibilityAttributes?: FCLAccessibilityAttributes;

  /**
   * Returns the current column layout, based on both the `layout` property and the screen size.
   *
   * **For example:** ["67%", "33%", 0], ["100%", 0, 0], ["25%", "50%", "25%"], etc,
   * where the numbers represents the width of the start, middle and end columns.
   */
  columnLayout?: FlexibleColumnLayoutColumnLayout | undefined;

  /**
   * Specifies if the user is allowed to change the columns layout by dragging the separator between the columns.
   */
  disableResizing?: boolean;

  /**
   * Returns if the `end` column is visible.
   */
  endColumnVisible?: boolean;

  /**
   * Defines the columns layout and their proportion.
   *
   * **Note:** The layout also depends on the screen size - one column for screens smaller than 599px,
   * two columns between 599px and 1023px and three columns for sizes bigger than 1023px.
   *
   * **For example:** layout=`TwoColumnsStartExpanded` means the layout will display up to two columns
   * in 67%/33% proportion.
   */
  layout?: FCLLayout | keyof typeof FCLLayout;

  /**
   * Allows to customize the column proportions per screen size and layout.
   * If no custom proportion provided for a specific layout, the default will be used.
   *
   * **Notes:**
   *
   * - The proportions should be given in percentages. For example ["30%", "40%", "30%"], ["70%", "30%", 0], etc.
   * - The proportions should add up to 100%.
   * - Hidden columns are marked as "0px", e.g. ["0px", "70%", "30%"]. Specifying 0 or "0%" for hidden columns is also valid.
   * - If the proportions do not match the layout (e.g. if provided proportions ["70%", "30%", "0px"] for "OneColumn" layout), then the default proportions will be used instead.
   * - Whenever the user drags the columns separator to resize the columns, the `layoutsConfiguration` object will be updated with the user-specified proportions for the given layout (and the `layout-configuration-change` event will be fired).
   * - No custom configuration available for the phone screen size, as the default of 100% column width is always used there.
   */
  layoutsConfiguration?: LayoutConfiguration;

  /**
   * Returns if the `middle` column is visible.
   */
  midColumnVisible?: boolean;

  /**
   * Returns if the `start` column is visible.
   */
  startColumnVisible?: boolean;

  /**
   * Returns the number of currently visible columns.
   */
  visibleColumns?: number;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * Implements the SAP Fiori Flexible Column Layout: up to three columns whose widths follow the current `layout` value.
       *
       * ```html
       * <furo-ui5-flexible-column-layout layout="TwoColumnsMidExpanded" style="height:300px">
       * <div slot="startColumn" style="padding:1rem">Master</div>
       * <div slot="midColumn" style="padding:1rem">Detail</div>
       * </furo-ui5-flexible-column-layout>
       * ```
       *
       * This is a pass-through wrapper around `furo-ui5-flexible-column-layout`: the UI5 API (properties, events,
       * slots) is inherited unchanged and no data binding is added.
       *
       * ### Overview
       *
       * The `FlexibleColumnLayout` implements the list-detail-detail paradigm by displaying up to three pages in separate columns.
       * There are several possible layouts that can be changed either with the component API, or by dragging the column separators.
       *
       * ### Usage
       *
       * Use this component for applications that need to display several logical levels of related information side by side (e.g. list of items, item, sub-item, etc.).
       * The Component is flexible in a sense that the application can focus the user's attention on one particular column.
       *
       * ### Responsive Behavior
       *
       * The `FlexibleColumnLayout` automatically displays the maximum possible number of columns based on `layout` property and the window size.
       * The component would display 1 column for window size smaller than 599px, up to two columns between 599px and 1023px,
       * and 3 columns for sizes bigger than 1023px.
       *
       * **Note:** When the component displays more than one column, the minimal width of each column is 248px. Consequently, when the user drags a column separator to resize the columns, the minimal allowed width of any resized column is 248px.
       *
       * ### Keyboard Handling
       *
       * #### Basic Navigation
       *
       * When a column separator is focused,  the following keyboard
       * shortcuts allow the user to resize the columns and change the layout:
       *
       * - [Shift] + [Left] or [Shift] + [Right] - Moves the separator to the left or right, which resizes the columns accordingly.
       * - [Left] or [Right] - Moves the separator to the left or right with a bigger step, which resizes the columns accordingly.
       * - [Home] - Moves the separator to the start position.
       * - [End] - Moves the separator to the end position.
       * - This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * #### Fast Navigation
       * This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/FlexibleColumnLayout.js";`
       *
       * ### Overview
       *
       * The `FlexibleColumnLayout` implements the list-detail-detail paradigm by displaying up to three pages in separate columns.
       * There are several possible layouts that can be changed either with the component API, or by dragging the column separators.
       *
       * ### Usage
       *
       * Use this component for applications that need to display several logical levels of related information side by side (e.g. list of items, item, sub-item, etc.).
       * The Component is flexible in a sense that the application can focus the user's attention on one particular column.
       *
       * ### Responsive Behavior
       *
       * The `FlexibleColumnLayout` automatically displays the maximum possible number of columns based on `layout` property and the window size.
       * The component would display 1 column for window size smaller than 599px, up to two columns between 599px and 1023px,
       * and 3 columns for sizes bigger than 1023px.
       *
       * **Note:** When the component displays more than one column, the minimal width of each column is 248px. Consequently, when the user drags a column separator to resize the columns, the minimal allowed width of any resized column is 248px.
       *
       * ### Keyboard Handling
       *
       * #### Basic Navigation
       *
       * When a column separator is focused,  the following keyboard
       * shortcuts allow the user to resize the columns and change the layout:
       *
       * - [Shift] + [Left] or [Shift] + [Right] - Moves the separator to the left or right, which resizes the columns accordingly.
       * - [Left] or [Right] - Moves the separator to the left or right with a bigger step, which resizes the columns accordingly.
       * - [Home] - Moves the separator to the start position.
       * - [End] - Moves the separator to the end position.
       * - This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * #### Fast Navigation
       * This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/FlexibleColumnLayout.js";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-flexible-column-layout": FlexibleColumnLayout;
    }
  }
}
