// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type * as React from "react";

import type IconShape from "../types/IconShape";
import type IconSize from "../types/IconSize";

export interface HeaderPanel extends React.HTMLAttributes<HTMLElement> {
  "onfavorite-icon-clicked"?: (d: CustomEvent<HTMLElement>) => void;
  onhid?: (d: CustomEvent<boolean>) => void;
  "onobject-icon-clicked"?: (d: CustomEvent<HTMLElement>) => void;
  onpinned?: (d: CustomEvent) => void;
  onshowed?: (d: CustomEvent<boolean>) => void;
  onunpinned?: (d: CustomEvent) => void;
  "onvariant-icon-clicked"?: (d: CustomEvent<HTMLElement>) => void;
  // properties

  // attributes

  /**
   * Set this attribute to get a bigger action slot.
   */
  bigAction?: boolean;

  /**
   * Flag to disable/enable collapsing/expanding on scroll
   */
  collapseOnScroll?: boolean;

  /**
   * Set the collapsed attribute to start in a collapsed state. Header which are pinned by the user in collapsed or expanded state, will override
   * this attribute.
   */
  collapsed?: boolean;

  /**
   * Fixes the header as it is. This will remove the collapse and expand buttons.
   *
   * Programmatic expand and collapse will still work.
   */
  fixed?: boolean;

  /**
   * Defines the headerText of the component.
   */
  headerText?: string;

  /**
   * Defines the headerTextLevel of the component.
   */
  headerTextLevel?: string;

  /**
   * Defines the icon of the component.
   *
   * To change the size use `icon-size`.
   *
   * To change the shape use `icon-shape`.
   */
  icon?: string;

  /**
   * Defines the icon-shape of the icon / image.
   * Square | Circle
   */
  iconShape?: IconShape | keyof typeof IconShape;

  /**
   * Defines the icon-size of the icon / image.
   *
   * S, M, L, XL
   */
  iconSize?: IconSize | keyof typeof IconSize;

  /**
   * Defines the image of the component.
   * In the case that an image and an icon are set, only the icon is displayed.
   */
  image?: string;

  /**
   * Shows the fovorite icon when set.
   */
  isFavorite?: boolean;

  /**
   * Set the is-pinned attribute to disable collapse and expand before unpin.
   */
  isPinned?: boolean;

  /**
   * Set this value to display an object icon.
   */
  objectIcon?: string;

  /**
   * The secondary text is something like a subtitle, it is placed below the header text and KPI slot.
   * If the secondary text is empty, the label is removed.
   */
  secondaryText?: string;

  /**
   * Draw a shadow, this is useful when you do not have a `tab-container` after your `dynamic-header`
   */
  shadow?: boolean;

  /**
   * Show the dropdown button icon after the header text.
   */
  showDropdown?: boolean;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       *
       * ### Overview
       * The dynamic page header contains key information about the object and provides the user with the necessary context. The header initially expands in display mode. It also contains global actions for the object, such as Edit or Delete.
       *
       * ### Usage
       * #### Header Content (default slot)
       * The header content displays app-specific contextual information. You build the content using containers, called facets.
       *
       * The facets are arranged inline with a left float. Each facet adapts its size to the content and makes optimal use of the space without truncating the texts. If the facets do not all fit on one line, those on the right wrap to the line below.
       *
       * <strong>Note:</strong> The Breadcrumb and the TabContainer is not part of the DynamicHeader component.
       *
       * <a href="https://experience.sap.com/fiori-design-web/dynamic-page-layout/#components">Read more about the DynamicHeader in the DynamicPage page layout.</a>
       *
       * <a href="https://experience.sap.com/fiori-design-web/object-page/#dynamic-page-header-mandatory">Read more about the DynamicHeader in the ObjectPage floor plan.</a>
       */
      "furo-ui5-header-panel": HeaderPanel;
    }
  }
}
