// DO NOT EDIT this file was generated with scripts/IntrinsicElements

import type {
  ListAccessibilityAttributes,
  ListItemClickEventDetail,
  ListItemCloseEventDetail,
  ListItemDeleteEventDetail,
  ListItemToggleEventDetail,
  ListMoveEventDetail,
  ListSelectionChangeEventDetail,
} from "@ui5/webcomponents/dist/List.js";
import type ListItemBase from "@ui5/webcomponents/dist/ListItemBase.js";
import type ListAccessibleRole from "@ui5/webcomponents/dist/types/ListAccessibleRole.js";
import type ListGrowingMode from "@ui5/webcomponents/dist/types/ListGrowingMode.js";
import type ListSelectionMode from "@ui5/webcomponents/dist/types/ListSelectionMode.js";
import type ListSeparator from "@ui5/webcomponents/dist/types/ListSeparator.js";
import * as React from "react";

export interface List extends React.HTMLAttributes<HTMLElement> {
  "onitem-click"?: (d: CustomEvent<ListItemClickEventDetail>) => void;
  "onitem-close"?: (d: CustomEvent<ListItemCloseEventDetail>) => void;
  "onitem-delete"?: (d: CustomEvent<ListItemDeleteEventDetail>) => void;
  "onitem-toggle"?: (d: CustomEvent<ListItemToggleEventDetail>) => void;
  "onload-more"?: (d: CustomEvent) => void;
  onmove?: (d: CustomEvent<ListMoveEventDetail>) => void;
  "onmove-over"?: (d: CustomEvent<ListMoveEventDetail>) => void;
  "onselection-change"?: (d: CustomEvent<ListSelectionChangeEventDetail>) => void;
  // properties

  // attributes

  /**
   * Defines additional accessibility attributes on different areas of the component.
   *
   * The accessibilityAttributes object has the following field:
   *
   * - **growingButton**: `growingButton.name`, `growingButton.description`.
   *
   * The accessibility attributes support the following values:
   *
   * - **name**: Defines the accessible ARIA name of the growing button.
   * Accepts any string.
   *
   * - **description**: Defines the accessible ARIA description of the growing button.
   * Accepts any string.
   *
   * **Note:** The `accessibilityAttributes` property is in an experimental state and is a subject to change.
   */
  accessibilityAttributes?: ListAccessibilityAttributes;

  /**
   * Defines the accessible description of the component.
   */
  accessibleDescription?: string | undefined;

  /**
   * Defines the IDs of the elements that describe the component.
   */
  accessibleDescriptionRef?: string | undefined;

  /**
   * Defines the accessible name of the component.
   */
  accessibleName?: string | undefined;

  /**
   * Defines the IDs of the elements that label the component.
   */
  accessibleNameRef?: string | undefined;

  /**
   * Defines the accessible role of the component.
   */
  accessibleRole?: ListAccessibleRole | keyof typeof ListAccessibleRole;

  /**
   * Defines the footer text.
   */
  footerText?: string | undefined;

  /**
   * Defines whether the component will have growing capability either by pressing a `More` button,
   * or via user scroll. In both cases `load-more` event is fired.
   *
   * **Restrictions:** `growing="Scroll"` is not supported for Internet Explorer,
   * on IE the component will fallback to `growing="Button"`.
   */
  growing?: ListGrowingMode | keyof typeof ListGrowingMode;

  /**
   * Defines the text that will be displayed inside the growing button.
   *
   * **Note:** If not specified a built-in text will be displayed.
   *
   * **Note:** This property takes effect if the `growing` property is set to the `Button`.
   */
  growingButtonText?: string | undefined;

  /**
   * Defines the component header text.
   *
   * **Note:** If `header` is set this property is ignored.
   */
  headerText?: string | undefined;

  /**
   * Determines whether the component is indented.
   */
  indent?: boolean;

  /**
   * Returns an array containing the list item instances without the groups in a flat structure.
   */
  listItems?: ListItemBase[];

  /**
   * Defines if the component would display a loading indicator over the list.
   */
  loading?: boolean;

  /**
   * Defines the delay in milliseconds, after which the loading indicator will show up for this component.
   */
  loadingDelay?: number;

  /**
   * Defines the text that is displayed when the component contains no items.
   */
  noDataText?: string | undefined;

  /**
   * Defines the selection mode of the component.
   */
  selectionMode?: ListSelectionMode | keyof typeof ListSelectionMode;

  /**
   * Defines the item separator style that is used.
   */
  separators?: ListSeparator | keyof typeof ListSeparator;

  /**
   * Indicates whether the List header is sticky or not.
   * If stickyHeader is set to true, then whenever you scroll the content or
   * the application, the header of the list will be always visible.
   */
  stickyHeader?: boolean;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The 'furo-ui5-list' is a thin wrapper around the
       * [SAP ui5 List element](https://ui5.github.io/webcomponents/components/List/).
       *
       * It exposes the full UI5 List API unchanged. There is intentionally **no data binding** — place
       * `furo-ui5-li*` items as children yourself.
       *
       * ### Overview
       *
       * The `furo-ui5-list` component allows displaying a list of items, advanced keyboard
       * handling support for navigating between items, and predefined modes to improve the development efficiency.
       *
       * The `furo-ui5-list` is a container for the available list items:
       *
       * - `furo-ui5-li`
       * - `furo-ui5-li-custom`
       * - `furo-ui5-li-group`
       *
       * To benefit from the built-in selection mechanism, you can use the available
       * selection modes, such as
       * `Single`, `Multiple` and `Delete`.
       *
       * Additionally, the `furo-ui5-list` provides header, footer, and customization for the list item separators.
       *
       * ### Keyboard Handling
       *
       * #### Basic Navigation
       * The `furo-ui5-list` provides advanced keyboard handling.
       * When a list is focused the user can use the following keyboard
       * shortcuts in order to perform a navigation:
       *
       * - [Up] or [Down] - Navigates up and down the items
       * - [Home] - Navigates to first item
       * - [End] - Navigates to the last item
       *
       * The user can use the following keyboard shortcuts to perform actions (such as select, delete),
       * when the `selectionMode` property is in use:
       *
       * - [Space] - Select an item (if `type` is 'Active') when `selectionMode` is selection
       * - [Delete] - Delete an item if `selectionMode` property is `Delete`
       *
       * #### Fast Navigation
       * This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/List.js";`
       *
       * `import "@furo/ui5/dist/ListItemStandard.js";` (for `furo-ui5-li`)
       *
       * `import "@furo/ui5/dist/ListItemCustom.js";` (for `furo-ui5-li-custom`)
       *
       * `import "@furo/ui5/dist/ListItemGroup.js";` (for `furo-ui5-li-group`)
       *
       * ### Overview
       *
       * The `furo-ui5-list` component allows displaying a list of items, advanced keyboard
       * handling support for navigating between items, and predefined modes to improve the development efficiency.
       *
       * The `furo-ui5-list` is a container for the available list items:
       *
       * - `furo-ui5-li`
       * - `furo-ui5-li-custom`
       * - `furo-ui5-li-group`
       *
       * To benefit from the built-in selection mechanism, you can use the available
       * selection modes, such as
       * `Single`, `Multiple` and `Delete`.
       *
       * Additionally, the `furo-ui5-list` provides header, footer, and customization for the list item separators.
       *
       * ### Keyboard Handling
       *
       * #### Basic Navigation
       * The `furo-ui5-list` provides advanced keyboard handling.
       * When a list is focused the user can use the following keyboard
       * shortcuts in order to perform a navigation:
       *
       * - [Up] or [Down] - Navigates up and down the items
       * - [Home] - Navigates to first item
       * - [End] - Navigates to the last item
       *
       * The user can use the following keyboard shortcuts to perform actions (such as select, delete),
       * when the `selectionMode` property is in use:
       *
       * - [Space] - Select an item (if `type` is 'Active') when `selectionMode` is selection
       * - [Delete] - Delete an item if `selectionMode` property is `Delete`
       *
       * #### Fast Navigation
       * This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/List.js";`
       *
       * `import "@furo/ui5/dist/ListItemStandard.js";` (for `furo-ui5-li`)
       *
       * `import "@furo/ui5/dist/ListItemCustom.js";` (for `furo-ui5-li-custom`)
       *
       * `import "@furo/ui5/dist/ListItemGroup.js";` (for `furo-ui5-li-group`)
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-list": List;
    }
  }
}
