// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type NavigationLayoutMode from "@ui5/webcomponents-fiori/dist/types/NavigationLayoutMode.js";
import * as React from "react";

export interface NavigationLayout extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties

  // attributes

  /**
   * Specifies the navigation layout mode.
   */
  mode?: NavigationLayoutMode | keyof typeof NavigationLayoutMode;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The application frame: a `header` slot for the shellbar, a `sideContent` slot for the side navigation and a default slot for the page content.
       *
       * ```html
       * <furo-ui5-navigation-layout style="height:320px">
       * <furo-ui5-shellbar slot="header" primary-title="My App"></furo-ui5-shellbar>
       * <furo-ui5-side-navigation slot="sideContent">
       * <furo-ui5-side-navigation-item text="Home" icon="home" selected></furo-ui5-side-navigation-item>
       * <furo-ui5-side-navigation-item text="Reports" icon="bar-chart"></furo-ui5-side-navigation-item>
       * </furo-ui5-side-navigation>
       * <div style="padding:1rem">Page content</div>
       * </furo-ui5-navigation-layout>
       * ```
       *
       * This is a pass-through wrapper around `furo-ui5-navigation-layout`: the UI5 API (properties, events,
       * slots) is inherited unchanged and no data binding is added.
       *
       * ### Overview
       *
       * The `furo-ui5-navigation-layout` is a container component that can be used to
       * create a layout with a header, a side navigation and a content area.
       *
       * ### Usage
       *
       * Use the `furo-ui5-navigation-layout` to create whole screen of an application with vertical navigation.
       *
       * ### Responsive Behavior
       *
       * On larger screens with a width of 600px or more, excluding mobile phone devices, the side navigation is visible
       * by default and can be expanded or collapsed using the `mode` property.
       * On mobile phone devices and screens with a width of 599px or less, the side navigation is hidden by
       * default and can be displayed using the `mode` property.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/NavigationLayout.js";`
       *
       * ### Overview
       *
       * The `furo-ui5-navigation-layout` is a container component that can be used to
       * create a layout with a header, a side navigation and a content area.
       *
       * ### Usage
       *
       * Use the `furo-ui5-navigation-layout` to create whole screen of an application with vertical navigation.
       *
       * ### Responsive Behavior
       *
       * On larger screens with a width of 600px or more, excluding mobile phone devices, the side navigation is visible
       * by default and can be expanded or collapsed using the `mode` property.
       * On mobile phone devices and screens with a width of 599px or less, the side navigation is hidden by
       * default and can be displayed using the `mode` property.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/NavigationLayout.js";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-navigation-layout": NavigationLayout;
    }
  }
}
