// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type { ARRAY, ENUM, STRING, StringValue } from "@furo/open-models/";
import type ISegmentedButtonItem from "@ui5/webcomponents/dist/SegmentedButton.js";
import type { SegmentedButtonSelectionChangeEventDetail } from "@ui5/webcomponents/dist/SegmentedButton.js";
import type SegmentedButtonSelectionMode from "@ui5/webcomponents/dist/types/SegmentedButtonSelectionMode.js";
import * as React from "react";

import type { IdentifiableList, OptionLikeList, SelectOption } from "../index";

import type { FuroFatString, IFuroFatString } from "@/models/index.js";

export interface SegmentedButton extends React.HTMLAttributes<HTMLElement> {
  "onselection-change"?: (d: CustomEvent<SegmentedButtonSelectionChangeEventDetail>) => void;
  // properties

  /**
   * Use this to bind a model field by attribute.
   */
  model?: ENUM<unknown> | STRING | FuroFatString | StringValue | ARRAY<STRING, string> | ARRAY<FuroFatString, IFuroFatString> | IdentifiableList;

  /**
   * Use this to set and render the optionList as an attribute.
   */
  optionList?: SelectOption[] | undefined;

  /**
   * Use this to bind an options field by attribute.
   */
  optionsModel?: OptionLikeList | undefined;

  /**
   * The id (`data-id`) of the currently selected item — drives the single-selection bindings.
   */
  selectedId?: string;

  // attributes

  /**
   * Defines the accessible description of the component.
   */
  accessibleDescription?: string | undefined;

  /**
   * Defines the IDs of the HTML Elements that describe the component.
   */
  accessibleDescriptionRef?: string | undefined;

  /**
   * Defines the accessible ARIA name of the component.
   */
  accessibleName?: string | undefined;

  /**
   * Defines the IDs of the HTML Elements that label the component.
   */
  accessibleNameRef?: string | undefined;

  /**
   * Determines whether the segmented button items should be sized to fit their content.
   *
   * If set to `true`, each item will be sized to fit its content, with any extra space distributed after the last item.
   * If set to `false` (the default), all items will be equally sized to fill the available space.
   */
  itemsFitContent?: boolean;

  /**
   * Returns an array of the currently selected items.
   */
  selectedItems?: ISegmentedButtonItem[];

  /**
   * Defines the component selection mode.
   */
  selectionMode?: SegmentedButtonSelectionMode | keyof typeof SegmentedButtonSelectionMode;

  /**
   * Allows you to select the `unspecified` option of an enum.
   */
  showUnspecifiedOption?: boolean;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       *
       * The furo-furo-furo-ui5-segmented-button component shows a group of items. When the user clicks an item it stays
       * pressed. It extends the UI5 SegmentedButton and adds `bindData()` support for several model shapes:
       *
       * - **ENUM** — single selection; the items are generated from the enum descriptor (like `furo-furo-furo-ui5-select-enum`).
       * - **STRING | FuroFatString | StringValue** — single selection (`selectionMode="Single"`, like `furo-furo-furo-ui5-select`).
       * - **ARRAY&lt;STRING&gt; | ARRAY&lt;FuroFatString&gt; | IdentifiableList** — multiple selection
       * (`selectionMode="Multiple"`, like `furo-furo-furo-ui5-multi-combobox`).
       *
       * It also works without any data binding — just declare `furo-furo-ui5-segmented-button-item` children yourself.
       *
       * ### Possible ways to set the item list (for STRING / ARRAY bindings)
       * - Use `bindOptions()` or `optionsModel=` to bind a RepeaterNode as an item list.
       * - Add the items manually to the html.
       *
       * The bound value is mapped to the item's `data-id` attribute.
       *
       * ```html
       * <furo-furo-furo-ui5-segmented-button
       * .model="${this.model.choice}"
       * .optionsModel="${this.options}">
       * </furo-furo-furo-ui5-segmented-button>
       * ```
       *
       * ### Overview
       *
       * The `furo-furo-ui5-segmented-button` shows a group of items. When the user clicks or taps
       * one of the items, it stays in a pressed state. It automatically resizes the items
       * to fit proportionally within the component. When no width is set, the component uses the available width.
       *
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/SegmentedButton.js";`
       *
       * ### Overview
       *
       * The `furo-ui5-segmented-button` shows a group of items. When the user clicks or taps
       * one of the items, it stays in a pressed state. It automatically resizes the items
       * to fit proportionally within the component. When no width is set, the component uses the available width.
       *
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/SegmentedButton.js";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-segmented-button": SegmentedButton;
    }
  }
}
