// DO NOT EDIT this file was generated with scripts/IntrinsicElements

import type { ENUM } from "@furo/open-models/";
import type { IOption, SelectChangeEventDetail, SelectLiveChangeEventDetail } from "@ui5/webcomponents/dist/Select.js";
import type SelectTextSeparator from "@ui5/webcomponents/dist/types/SelectTextSeparator.js";
import type ValueState from "@ui5/webcomponents-base/dist/types/ValueState.js";
import * as React from "react";

export interface SelectEnum extends React.HTMLAttributes<HTMLElement> {
  onchange?: (d: CustomEvent<SelectChangeEventDetail>) => void;
  onclose?: (d: CustomEvent) => void;
  "onlive-change"?: (d: CustomEvent<SelectLiveChangeEventDetail>) => void;
  onopen?: (d: CustomEvent) => void;
  // properties

  // undocumented
  model?: ENUM<unknown> | undefined;

  // attributes

  /**
   * Defines the accessible description of the component.
   */
  accessibleDescription?: string | undefined;

  /**
   * Receives id(or many ids) of the elements that describe the select.
   */
  accessibleDescriptionRef?: string | undefined;

  /**
   * Defines the accessible ARIA name of the component.
   */
  accessibleName?: string | undefined;

  /**
   * Receives id(or many ids) of the elements that label the select.
   */
  accessibleNameRef?: string | undefined;

  /**
   * Defines whether the component is in disabled state.
   *
   * **Note:** A disabled component is noninteractive.
   */
  disabled?: boolean;

  /**
   * Determines the name by which the component will be identified upon submission in an HTML form.
   *
   * **Note:** This property is only applicable within the context of an HTML Form element.
   */
  name?: string | undefined;

  /**
   * Defines whether the component is read-only.
   *
   * **Note:** A read-only component is not editable,
   * but still provides visual feedback upon user interaction.
   */
  readonly?: boolean;

  /**
   * Defines whether the component is required.
   */
  required?: boolean;

  /**
   * Currently selected `furo-furo-ui5-option` element.
   */
  selectedOption?: IOption | undefined;

  /**
   * Allows you to select the `unspecified` option.
   */
  showUnspecifiedOption?: boolean;

  /**
   * Defines the separator type for the two columns layout when Select is in read-only mode.
   */
  textSeparator?: SelectTextSeparator | keyof typeof SelectTextSeparator;

  /**
   * Defines the tooltip of the select.
   */
  tooltip?: string | undefined;

  /**
   * Defines the value of the component:
   *
   * - when get - returns the value of the component or the value/text content of the selected option.
   * - when set - selects the option with matching `value` property or text content.
   *
   * **Note:** Use either the Select's value or the Options' selected property.
   * Mixed usage could result in unexpected behavior.
   *
   * **Note:** If the given value does not match any existing option,
   * no option will be selected and the Select component will be displayed as empty.
   */
  value?: string;

  /**
   * Defines the value state of the component.
   */
  valueState?: ValueState | keyof typeof ValueState;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       *
       * ### FuroUi5SelectEnum
       * With FuroUi5SelectEnum you can bind a ENUM field to the model. It will build up all defined options from the ENUM.
       *
       * It extends the UI5 Select.
       *
       * ---
       *
       * ### Overview
       *
       * The `furo-furo-ui5-select` component is used to create a drop-down list.
       *
       * ### Usage
       *
       * There are two main usages of the `furo-furo-ui5-select>`.
       *
       * - With Option (`furo-furo-ui5-option`) web component:
       *
       * The available options of the Select are defined by using the Option component.
       * The Option comes with predefined design and layout, including `icon`, `text` and `additional-text`.
       *
       * - With OptionCustom (`furo-furo-ui5-option-custom`) web component.
       *
       * Options with custom content are defined by using the OptionCustom component.
       * The OptionCustom component comes with no predefined layout and it expects consumers to define it.
       *
       * ### Selection
       *
       * The options can be selected via user interaction (click or with the use of the Space and Enter keys)
       * and programmatically - the Select component supports two distinct selection APIs, though mixing them is not supported:
       * - The "value" property of the Select component
       * - The "selected" property on individual options
       *
       * **Note:** If the "value" property is set but does not match any option,
       * no option will be selected and the Select component will be displayed as empty.
       *
       * **Note:** when both "value" and "selected" are both used (although discouraged),
       * the "value" property will take precedence.
       *
       * ### Keyboard Handling
       *
       * The `furo-furo-ui5-select` provides advanced keyboard handling.
       *
       * - [F4] / [Alt] + [Up] / [Alt] + [Down] / [Space] or [Enter] - Opens/closes the drop-down.
       * - [Up] or [Down] - If the drop-down is closed - changes selection to the next or the previous option. If the drop-down is opened - moves focus to the next or the previous option.
       * - [Space], [Enter] - If the drop-down is opened - selects the focused option.
       * - [Escape] - Closes the drop-down without changing the selection.
       * - [Home] - Navigates to first option
       * - [End] - Navigates to the last option
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/Select";`
       *
       * `import "@furo/ui5/dist/Option";`
       * `import "@furo/ui5/dist/OptionCustom";`
       *
       * ### Overview
       *
       * The `furo-ui5-select` component is used to create a drop-down list.
       *
       * ### Usage
       *
       * There are two main usages of the `furo-ui5-select>`.
       *
       * - With Option (`furo-ui5-option`) web component:
       *
       * The available options of the Select are defined by using the Option component.
       * The Option comes with predefined design and layout, including `icon`, `text` and `additional-text`.
       *
       * - With OptionCustom (`furo-ui5-option-custom`) web component.
       *
       * Options with custom content are defined by using the OptionCustom component.
       * The OptionCustom component comes with no predefined layout and it expects consumers to define it.
       *
       * ### Selection
       *
       * The options can be selected via user interaction (click or with the use of the Space and Enter keys)
       * and programmatically - the Select component supports two distinct selection APIs, though mixing them is not supported:
       * - The "value" property of the Select component
       * - The "selected" property on individual options
       *
       * **Note:** If the "value" property is set but does not match any option,
       * no option will be selected and the Select component will be displayed as empty.
       *
       * **Note:** when both "value" and "selected" are both used (although discouraged),
       * the "value" property will take precedence.
       *
       * ### Keyboard Handling
       *
       * The `furo-ui5-select` provides advanced keyboard handling.
       *
       * - [F4] / [Alt] + [Up] / [Alt] + [Down] / [Space] or [Enter] - Opens/closes the drop-down.
       * - [Up] or [Down] - If the drop-down is closed - changes selection to the next or the previous option. If the drop-down is opened - moves focus to the next or the previous option.
       * - [Space], [Enter] - If the drop-down is opened - selects the focused option.
       * - [Escape] - Closes the drop-down without changing the selection.
       * - [Home] - Navigates to first option
       * - [End] - Navigates to the last option
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/Select";`
       *
       * `import "@furo/ui5/dist/Option";`
       * `import "@furo/ui5/dist/OptionCustom";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-select-enum": SelectEnum;
    }
  }
}
