// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type * as React from "react";

export interface ShellBarSpacer extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties
  // attributes
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       *
       *
       * ### Overview
       * The `furo-ui5-shellbar-spacer` is an element, used for visual separation between the two content parts of the `furo-ui5-shellbar`.
       * **Note:** The `furo-ui5-shellbar-spacer` component is in an experimental state and is a subject to change.
       *
       * ### Overview
       * The `furo-ui5-shellbar-spacer` is an element, used for visual separation between the two content parts of the `furo-ui5-shellbar`.
       * **Note:** The `furo-ui5-shellbar-spacer` component is in an experimental state and is a subject to change.
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-shellbar-spacer": ShellBarSpacer;
    }
  }
}
