// DO NOT EDIT this file was generated with scripts/IntrinsicElements

import type ITab from "@ui5/webcomponents/dist/TabContainer.js";
import type { TabContainerMoveEventDetail, TabContainerTabSelectEventDetail } from "@ui5/webcomponents/dist/TabContainer.js";
import type BackgroundDesign from "@ui5/webcomponents/dist/types/BackgroundDesign.js";
import type OverflowMode from "@ui5/webcomponents/dist/types/OverflowMode.js";
import type TabLayout from "@ui5/webcomponents/dist/types/TabLayout.js";
import type * as React from "react";

export interface Tabcontainer extends React.HTMLAttributes<HTMLElement> {
  onmove?: (d: CustomEvent<TabContainerMoveEventDetail>) => void;
  "onmove-over"?: (d: CustomEvent<TabContainerMoveEventDetail>) => void;
  "ontab-select"?: (d: CustomEvent<TabContainerTabSelectEventDetail>) => void;
  // properties

  // attributes

  /**
   * Returns all slotted tabs and their subTabs in a flattened array.
   * The order of tabs is depth-first.
   */
  allItems?: ITab[];

  /**
   * Defines whether the tab content is collapsed.
   */
  collapsed?: boolean;

  /**
   * Sets the background color of the Tab Container's content as `Solid`, `Transparent`, or `Translucent`.
   */
  contentBackgroundDesign?: BackgroundDesign | keyof typeof BackgroundDesign;

  /**
   * Sets the background color of the Tab Container's header as `Solid`, `Transparent`, or `Translucent`.
   */
  headerBackgroundDesign?: BackgroundDesign | keyof typeof BackgroundDesign;

  /**
   * Defines if automatic tab selection is deactivated.
   *
   * **Note:** By default, if none of the child tabs have the `selected` property set, the first tab will be automatically selected.
   * Setting this property to `true` allows preventing this behavior.
   */
  noAutoSelection?: boolean;

  /**
   * Defines the overflow mode of the header (the tab strip). If you have a large number of tabs, only the tabs that can fit on screen will be visible.
   * All other tabs that can 't fit on the screen are available in an overflow tab "More".
   *
   * **Note:**
   * Only one overflow at the end would be displayed by default,
   * but when set to `StartAndEnd`, there will be two overflows on both ends, and tab order will not change on tab selection.
   */
  overflowMode?: OverflowMode | keyof typeof OverflowMode;

  /**
   * Defines the alignment of the content and the `additionalText` of a tab.
   *
   * **Note:**
   * The content and the `additionalText` would be displayed vertically by default,
   * but when set to `Inline`, they would be displayed horizontally.
   */
  tabLayout?: TabLayout | keyof typeof TabLayout;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The 'furo-ui5-tabcontainer' is a thin wrapper around the
       * [SAP ui5 TabContainer element](https://ui5.github.io/webcomponents/components/TabContainer/).
       *
       * It exposes the full UI5 TabContainer API unchanged. There is intentionally **no data binding** —
       * place `furo-ui5-tab` children yourself.
       *
       * ### Overview
       *
       * The `furo-ui5-tabcontainer` represents a collection of tabs with associated content.
       * Navigation through the tabs changes the content display of the currently active content area.
       * A tab can be labeled with text only, or icons with text.
       *
       * ### Structure
       *
       * The `furo-ui5-tabcontainer` can hold two types of entities:
       *
       * - `furo-ui5-tab` - contains all the information on an item (text and icon)
       * - `furo-ui5-tab-separator` - used to separate tabs with a line
       *
       * ### Hierarchies
       * Multiple sub tabs could be placed underneath one main tab. Nesting allows deeper hierarchies with indentations
       * to indicate the level of each nested tab. When a tab has both sub tabs and own content its click area is split
       * to allow the user to display the content or alternatively to expand / collapse the list of sub tabs.
       *
       * ### Keyboard Handling
       *
       * #### Fast Navigation
       * This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/TabContainer.js";`
       *
       * `import "@furo/ui5/dist/Tab.js";` (for `furo-ui5-tab`)
       *
       * `import "@furo/ui5/dist/TabSeparator.js";` (for `furo-ui5-tab-separator`)
       *
       * ### Overview
       *
       * The `furo-ui5-tabcontainer` represents a collection of tabs with associated content.
       * Navigation through the tabs changes the content display of the currently active content area.
       * A tab can be labeled with text only, or icons with text.
       *
       * ### Structure
       *
       * The `furo-ui5-tabcontainer` can hold two types of entities:
       *
       * - `furo-ui5-tab` - contains all the information on an item (text and icon)
       * - `furo-ui5-tab-separator` - used to separate tabs with a line
       *
       * ### Hierarchies
       * Multiple sub tabs could be placed underneath one main tab. Nesting allows deeper hierarchies with indentations
       * to indicate the level of each nested tab. When a tab has both sub tabs and own content its click area is split
       * to allow the user to display the content or alternatively to expand / collapse the list of sub tabs.
       *
       * ### Keyboard Handling
       *
       * #### Fast Navigation
       * This component provides a build in fast navigation group which can be used via [F6] / [Shift] + [F6] / [Ctrl] + [Alt/Option] / [Down] or [Ctrl] + [Alt/Option] + [Up].
       * In order to use this functionality, you need to import the following module:
       * `import "@ui5/webcomponents-base/dist/features/F6Navigation.js"`
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/TabContainer.js";`
       *
       * `import "@furo/ui5/dist/Tab.js";` (for `furo-ui5-tab`)
       *
       * `import "@furo/ui5/dist/TabSeparator.js";` (for `furo-ui5-tab-separator`)
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-tabcontainer": Tabcontainer;
    }
  }
}
