// DO NOT EDIT this file was generated with scripts/IntrinsicElements

import type { STRING, StringValue } from "@furo/open-models/";
import type { InputSelectionChangeEventDetail } from "@ui5/webcomponents/dist/Input.js";
import type InputSuggestionsFilter from "@ui5/webcomponents/dist/types/InputSuggestionsFilter.js";
import type InputType from "@ui5/webcomponents/dist/types/InputType.js";
import type ValueState from "@ui5/webcomponents-base/dist/types/ValueState.js";
import * as React from "react";

import type { FuroFatString } from "@/models/index.js";

export interface TextInput extends React.HTMLAttributes<HTMLElement> {
  onchange?: (d: CustomEvent) => void;
  onclose?: (d: CustomEvent) => void;
  oninput?: (d: CustomEvent) => void;
  onopen?: (d: CustomEvent) => void;
  "onsearch-requested"?: (d: CustomEvent<string>) => void;
  onselect?: (d: CustomEvent) => void;
  "onselection-change"?: (d: CustomEvent<InputSelectionChangeEventDetail>) => void;
  // properties

  /**
   * Use this to bind a model field by attribute.
   */
  model?: STRING | FuroFatString | StringValue;

  // attributes

  /**
   * Defines the accessible description of the component.
   */
  accessibleDescription?: string | undefined;

  /**
   * Receives id(or many ids) of the elements that describe the input.
   */
  accessibleDescriptionRef?: string | undefined;

  /**
   * Defines the accessible ARIA name of the component.
   */
  accessibleName?: string | undefined;

  /**
   * Receives id(or many ids) of the elements that label the input.
   */
  accessibleNameRef?: string | undefined;

  /**
   * Defines whether the component is in disabled state.
   *
   * **Note:** A disabled component is completely noninteractive.
   */
  disabled?: boolean;

  /**
   * Defines the filter type of the component.
   */
  filter?: InputSuggestionsFilter | keyof typeof InputSuggestionsFilter;

  /**
   * Sets the maximum number of characters available in the input field.
   *
   * **Note:** This property is not compatible with the furo-furo-ui5-input type InputType.Number. If the furo-furo-ui5-input type is set to Number, the maxlength value is ignored.
   */
  maxlength?: number | undefined;

  /**
   * Determines the name by which the component will be identified upon submission in an HTML form.
   *
   * **Note:** This property is only applicable within the context of an HTML Form element.
   */
  name?: string | undefined;

  /**
   * Defines whether the value will be autcompleted to match an item
   */
  noTypeahead?: boolean;

  /**
   * Defines whether the suggestions picker is open.
   * The picker will not open if the `showSuggestions` property is set to `false`, the input is disabled or the input is readonly.
   * The picker will close automatically and `close` event will be fired if the input is not in the viewport.
   */
  open?: boolean;

  /**
   * Defines a short hint intended to aid the user with data entry when the
   * component has no value.
   */
  placeholder?: string | undefined;

  /**
   * Defines whether the component is read-only.
   *
   * **Note:** A read-only component is not editable,
   * but still provides visual feedback upon user interaction.
   */
  readonly?: boolean;

  /**
   * Defines whether the component is required.
   */
  required?: boolean;

  /**
   * Defines whether the clear icon of the input will be shown.
   */
  showClearIcon?: boolean;

  /**
   * Defines whether the component should show suggestions, if such are present.
   */
  showSuggestions?: boolean;

  /**
   * Defines the HTML type of the component.
   *
   * **Notes:**
   *
   * - The particular effect of this property differs depending on the browser
   * and the current language settings, especially for type `Number`.
   * - The property is mostly intended to be used with touch devices
   * that use different soft keyboard layouts depending on the given input type.
   * - Type `Number` does not support suggestions.
   */
  type?: InputType | keyof typeof InputType;

  /**
   * Defines the value of the component.
   *
   * **Note:** The property is updated upon typing.
   */
  value?: string;

  /**
   * Defines the value state of the component.
   */
  valueState?: ValueState | keyof typeof ValueState;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The 'furo-furo-furo-ui5-text-input' component allows the user to enter and edit texts with data binding.
       *
       * It supports all features from the [SAP ui5 Input element](https://sap.github.io/furo-furo-ui5-webcomponents/playground/components/Input/).
       *
       * You can bind any `string` type, like `furo.fat.String` type or the `google.protobuf.StringValue` type.
       * ## supported FAT attributes
       * - **"readonly":"true"** set the element to readonly
       * - **"required":"true"** set the element to required
       * - **"disabled":"true"** set the element to disabled
       * - **"icon":"home"** set the icon
       * - **"placeholder":"string"** set the placeholder for the element
       * - **"max":"number"** set the maximum number of characters available in the input field.
       *
       * ## supported meta and constraints
       * - **readonly: true** , set the element to readonly
       * - **placeholder:"some string"** set the placeholder for the element
       * - **max:"number"** set the maximum number of characters available in the input field.
       *
       * ### Overview
       *
       * The `furo-furo-ui5-input` component allows the user to enter and edit text or numeric values in one line.
       *
       * Additionally, you can provide `suggestionItems`
       * that are displayed in a popover right under the input. Keep in mind that `furo-furo-ui5-input` with type `Number` does not support suggestions.
       *
       * The text field can be editable or read-only (`readonly` property),
       * and it can be enabled or disabled (`disabled` property).
       * To visualize semantic states, such as "Negative" or "Critical", the `valueState` property is provided.
       * When the user makes changes to the text, the change event is fired,
       * which enables you to react on any text change.
       *
       * ### Keyboard Handling
       * The `furo-furo-ui5-input` provides the following keyboard shortcuts:
       *
       * - [Escape] - Closes the suggestion list, if open. If closed or not enabled, cancels changes and reverts to the value which the Input field had when it got the focus.
       * - [Enter] or [Return] - If suggestion list is open takes over the current matching item and closes it. If value state or group header is focused, does nothing.
       * - [Down] - Focuses the next matching item in the suggestion list. Selection-change event is fired.
       * - [Up] - Focuses the previous matching item in the suggestion list. Selection-change event is fired.
       * - [Home] - If focus is in the text input, moves caret before the first character. If focus is in the list, highlights the first item and updates the input accordingly.
       * - [End] - If focus is in the text input, moves caret after the last character. If focus is in the list, highlights the last item and updates the input accordingly.
       * - [Page Up] - If focus is in the list, moves highlight up by page size (10 items by default). If focus is in the input, does nothing.
       * - [Page Down] - If focus is in the list, moves highlight down by page size (10 items by default). If focus is in the input, does nothing.
       * - [Ctrl]+[Alt]+[F8] or [Command]+[Option]+[F8] - Focuses the first link in the value state message, if available. Pressing [Tab] moves the focus to the next link in the value state message, or closes the value state message if there are no more links.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/Input.js";`
       *
       * ### Overview
       *
       * The `furo-ui5-input` component allows the user to enter and edit text or numeric values in one line.
       *
       * Additionally, you can provide `suggestionItems`
       * that are displayed in a popover right under the input. Keep in mind that `furo-ui5-input` with type `Number` does not support suggestions.
       *
       * The text field can be editable or read-only (`readonly` property),
       * and it can be enabled or disabled (`disabled` property).
       * To visualize semantic states, such as "Negative" or "Critical", the `valueState` property is provided.
       * When the user makes changes to the text, the change event is fired,
       * which enables you to react on any text change.
       *
       * ### Keyboard Handling
       * The `furo-ui5-input` provides the following keyboard shortcuts:
       *
       * - [Escape] - Closes the suggestion list, if open. If closed or not enabled, cancels changes and reverts to the value which the Input field had when it got the focus.
       * - [Enter] or [Return] - If suggestion list is open takes over the current matching item and closes it. If value state or group header is focused, does nothing.
       * - [Down] - Focuses the next matching item in the suggestion list. Selection-change event is fired.
       * - [Up] - Focuses the previous matching item in the suggestion list. Selection-change event is fired.
       * - [Home] - If focus is in the text input, moves caret before the first character. If focus is in the list, highlights the first item and updates the input accordingly.
       * - [End] - If focus is in the text input, moves caret after the last character. If focus is in the list, highlights the last item and updates the input accordingly.
       * - [Page Up] - If focus is in the list, moves highlight up by page size (10 items by default). If focus is in the input, does nothing.
       * - [Page Down] - If focus is in the list, moves highlight down by page size (10 items by default). If focus is in the input, does nothing.
       * - [Ctrl]+[Alt]+[F8] or [Command]+[Option]+[F8] - Focuses the first link in the value state message, if available. Pressing [Tab] moves the focus to the next link in the value state message, or closes the value state message if there are no more links.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/Input.js";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-text-input": TextInput;
    }
  }
}
