// DO NOT EDIT this file was generated with scripts/IntrinsicElements

import type { STRING, StringValue } from "@furo/open-models/dist/index.js";
import * as React from "react";

import type { FuroFatString } from "@/models/index.js";

export interface Textarea extends React.HTMLAttributes<HTMLElement> {
  // no events defined.
  // properties

  /**
   * Use this to bind a model field by attribute.
   */
  model?: STRING | FuroFatString | StringValue;

  // attributes
  // no attributes defined.
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The 'furo-furo-furo-ui5-textarea' component allows the user to enter and edit texts with data binding.
       *
       * It supports all features from the [SAP ui5 Input element](https://sap.github.io/furo-furo-ui5-webcomponents/playground/components/Input/).
       *
       * You can bind any `string` type, like `furo.fat.String` type or the `google.protobuf.StringValue` type.
       * ## supported FAT attributes
       * - **"readonly":"true"** set the element to readonly
       * - **"required":"true"** set the element to required
       * - **"disabled":"true"** set the element to disabled
       * - **"icon":"home"** set the icon
       * - **"placeholder":"string"** set the placeholder for the element
       * - **"max":"number"** set the maximum number of characters available in the input field.
       *
       * ## supported meta and constraints
       * - **readonly: true** , set the element to readonly
       * - **placeholder:"some string"** set the placeholder for the element
       * - **max:"number"** set the maximum number of characters available in the input field.
       *
       * ### Overview
       *
       * The `furo-furo-ui5-textarea` component is used to enter multiple rows of text.
       *
       * When empty, it can hold a placeholder similar to a `furo-furo-ui5-input`.
       * You can define the rows of the `furo-furo-ui5-textarea` and also determine specific behavior when handling long texts.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/TextArea.js";`
       */
      "furo-ui5-textarea": Textarea;
    }
  }
}
