// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type ValueState from "@ui5/webcomponents-base/dist/types/ValueState.js";
import type * as React from "react";

export interface TimelineItem extends React.HTMLAttributes<HTMLElement> {
  "onname-click"?: (d: CustomEvent) => void;
  // properties

  // attributes

  /**
   * Defines the icon to be displayed as graphical element within the `furo-ui5-timeline-item`.
   * SAP-icons font provides numerous options.
   *
   * See all the available icons in the [Icon Explorer](https://sdk.openui5.org/test-resources/sap/m/demokit/iconExplorer/webapp/index.html).
   */
  icon?: string | undefined;

  /**
   * Defines the tooltip of the graphical icon.
   */
  iconTooltip?: string | undefined;

  /**
   * Defines the name of the item, displayed before the `title-text`.
   */
  name?: string | undefined;

  /**
   * Defines if the `name` is clickable.
   */
  nameClickable?: boolean;

  /**
   * Defines the state of the icon displayed in the `furo-ui5-timeline-item`.
   */
  state?: ValueState | keyof typeof ValueState;

  /**
   * Defines the subtitle text of the component.
   */
  subtitleText?: string | undefined;

  /**
   * Defines the title text of the component.
   */
  titleText?: string | undefined;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * One event of a `furo-ui5-timeline`, with a title, subtitle, icon and free content in the default slot.
       *
       * ```html
       * <furo-ui5-timeline>
       * <furo-ui5-timeline-item title-text="Approved" subtitle-text="2 days ago" icon="accept" name="Jane Doe">
       * Budget approved without changes.
       * </furo-ui5-timeline-item>
       * </furo-ui5-timeline>
       * ```
       *
       * This is a pass-through wrapper around `furo-ui5-timeline-item`: the UI5 API (properties, events,
       * slots) is inherited unchanged and no data binding is added.
       *
       * ### Overview
       *
       * An entry posted on the timeline.
       *
       * ### Overview
       *
       * An entry posted on the timeline.
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-timeline-item": TimelineItem;
    }
  }
}
