// DO NOT EDIT this file was generated with scripts/IntrinsicElements
import type ToastPlacement from "@ui5/webcomponents/dist/types/ToastPlacement.js";
import * as React from "react";

export interface Toast extends React.HTMLAttributes<HTMLElement> {
  onclose?: (d: CustomEvent) => void;
  // properties

  // attributes

  /**
   * Defines the duration in milliseconds for which component
   * remains on the screen before it's automatically closed.
   *
   * **Note:** The minimum supported value is `500` ms
   * and even if a lower value is set, the duration would remain `500` ms.
   */
  duration?: number;

  /**
   * Indicates whether the component is open (visible).
   */
  open?: boolean;

  /**
   * Defines the placement of the component.
   */
  placement?: ToastPlacement | keyof typeof ToastPlacement;
}

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      /**
       * The furo-ui5-toast is a extended furo-ui5-toast which can attach itself to a parent dom element.
       *
       * This is helpful, when you have used z-indexes in one of the parents, which put the original furo-ui5-toast behind the backdrop.
       *
       * Use this component like a regular furo-ui5-toast and do not forget to place the furo-ui5-toast-display in one of the parent elements.
       *
       * It supports all features from the [SAP ui5 Toast element](https://ui5.github.io/webcomponents/components/Toast/).
       *
       * **important:** Place a furo-ui5-toast-display in any dom parent of the component where you use furo-ui5-toast. Your app-shell or body is a good place to do that.
       *
       * ```html
       * <furo-ui5-toast  fn-show="--openToastClicked" placement="MiddleCenter">Content</furo-ui5-toast>
       *
       * <button at-click="--openToastClicked">Open toast</button>
       * ```
       *
       * ### Overview
       *
       * The `furo-ui5-toast` is a small, non-disruptive popup for success or information messages that
       * disappears automatically after a few seconds.
       *
       * ### Usage
       *
       * #### When to use:
       *
       * - You want to display a short success or information message.
       * - You do not want to interrupt users while they are performing an action.
       * - You want to confirm a successful action.
       *
       * #### When not to use:
       *
       * - You want to display error or warning message.
       * - You want to interrupt users while they are performing an action.
       * - You want to make sure that users read the message before they leave the page.
       * - You want users to be able to copy some part of the message text.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/Toast.js";`
       *
       * ### Overview
       *
       * The `furo-ui5-toast` is a small, non-disruptive popup for success or information messages that
       * disappears automatically after a few seconds.
       *
       * ### Usage
       *
       * #### When to use:
       *
       * - You want to display a short success or information message.
       * - You do not want to interrupt users while they are performing an action.
       * - You want to confirm a successful action.
       *
       * #### When not to use:
       *
       * - You want to display error or warning message.
       * - You want to interrupt users while they are performing an action.
       * - You want to make sure that users read the message before they leave the page.
       * - You want users to be able to copy some part of the message text.
       *
       * ### ES6 Module Import
       *
       * `import "@furo/ui5/dist/Toast.js";`
       *
       * Base class for all UI5 Web Components
       */
      "furo-ui5-toast": Toast;
    }
  }
}
