syntax = "proto3";

package furoui5test.cube;

option java_multiple_files = true;
option java_package = "pro.furoui5test.cube";
option go_package = "furoui5test/cube;cubepb";


import "furoui5test/cube/colours.proto";
import "furo/fat/fat.proto";
import "furoui5test/cube/enums.proto";

import "openapiv3/annotations.proto";

message CubeDefinition {
  option (openapi.v3.schema) = {required:['length', 'breadth','height']};
  double length = 1 [(openapi.v3.property) ={default:{number:120}, maximum: 1000, minimum: 100}];
  double breadth = 2 [(openapi.v3.property) ={default:{number:120}, maximum: 1000, minimum: 100}];
  double height = 3  [(openapi.v3.property) ={default:{number:120}, maximum: 1000, minimum: 100}];
  cube.Colour colour = 4;
  Materials material = 5;
  oneof op{
    string str = 6;
    bool boo = 7;
    int32 num = 8;
  };
  furo.fat.String fat_string = 9;
  int32 rating = 10 [(openapi.v3.property) ={default:{number:4}, maximum: 5, minimum: 0}];
}

message CubeEntity {
  string display_name = 1 [(openapi.v3.property) = {read_only:true}];
  string description = 2 [(openapi.v3.property) ={default:{string:"some"}, min_length: 5}];;
  CubeDefinition cube = 3 [(openapi.v3.property) = {default:{string:'{"length":222}'}}];
}

