#!/usr/bin/env node

/**
 * Generates `global.d.ts` — a side-effect import of every Furo custom element.
 *
 * lit-analyzer (@jackolope/ts-lit-plugin) learns custom element tag names from the
 * TypeScript program, via the `declare global { interface HTMLElementTagNameMap }`
 * block that each element's own `index.d.ts` carries. Without this file, an element
 * used in a template but not imported in that same file is reported as
 * "Unknown tag <x>. Did you mean <y>?" — a misleading rename suggestion.
 *
 * With every element registered here the tag is always known, so the diagnostic
 * becomes the accurate "Missing import for <x>" — `no-missing-import` still checks
 * imports per file, so genuinely forgotten imports are still caught.
 *
 * A .d.ts emits nothing, so there is no runtime or bundle cost.
 */

import fs from 'fs';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

const OUTFILE = './global.d.ts';

const PACKAGES = [
  {
    name: '@furo/ui5',
    // "./tabcontainer" -> "./dist/elements/tabcontainer/index.js"
    elementTarget: /^\.\/dist\/elements\/([^/]+)\/index\.js$/,
    // `types` correctly points at the index.d.ts holding the declare-global block,
    // so the clean public subpath works.
    specifier: element => `@furo/ui5/${element}`,
  },
  {
    name: '@furo/layout',
    // "./furo-vertical-flex" -> "./dist/components/furo-vertical-flex/index.js"
    elementTarget: /^\.\/dist\/components\/([^/]+)\/index\.js$/,
    // Needs @furo/layout >= 3.0.0-RC.12: RC.11 and earlier mapped `types` to the
    // *class* .d.ts (FuroVerticalFlex.d.ts) rather than the index.d.ts holding the
    // declare-global block, so the clean subpath never registered the tag.
    specifier: element => `@furo/layout/${element}`,
  },
];

const sections = [];
let total = 0;

for (const { name, elementTarget, specifier } of PACKAGES) {
  const pkg = require(`${name}/package.json`);

  // Only the per-element entry points carry the tag-name map. Everything else in the
  // exports map (".", "./models", "./JSX/*", "./styles/*", ...) is skipped.
  const elements = [];
  for (const [key, value] of Object.entries(pkg.exports ?? {})) {
    const target = typeof value === 'string' ? value : value?.default;
    if (typeof target !== 'string') continue;

    const match = elementTarget.exec(target);
    // Only accept the canonical form where the export key is the element directory,
    // so we never emit a specifier for something that isn't actually an element.
    if (match && key === `./${match[1]}`) elements.push(match[1]);
  }
  elements.sort();

  if (elements.length === 0) {
    console.log(`⚠️  No ${name} element subpaths found in the exports map!`);
    process.exit(1);
  }

  total += elements.length;
  sections.push(`// ${name} (${elements.length})\n${elements.map(e => `import "${specifier(e)}";`).join('\n')}`);
}

const contents = `// AUTO-GENERATED by scripts/GenerateFuroUi5Globals.mjs — do not edit.
// Regenerate with \`npm run build:codecompletion\`.
//
// Registers every Furo element's HTMLElementTagNameMap entry with the TypeScript
// program so lit-analyzer knows the tag names. Type-only, emits nothing.

${sections.join('\n\n')}
`;

fs.writeFileSync(OUTFILE, contents);

console.log(`✅  global.d.ts generated (${total} Furo elements).`);
