// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ARRAY, BOOLEAN, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface INavigationnode
 *  Item of the navigation tree.
 */
export interface INavigationnode {
  /**
   *  Id of the node.
   */
  id?: string;
  /**
   *  String representation of the node.
   */
  displayName?: string;
  /**
   *  Children of this node.
   */
  children?: INavigationnode[];
  /**
   *  Node is open or not.
   */
  open?: boolean;
  /**
   *  Secondary text of the node. [optional]
   */
  secondaryText?: string;
  /**
   *  Searchable description of the node. [optional]
   */
  description?: string;
  /**
   *  Icon of the node. [optional]
   */
  icon?: string;
  /**
   *  Searchable key words of the node. [optional]
   */
  keyWords?: string;
  /**
   *  Error indicator. [optional]
   */
  hasError?: boolean;
  /**
   *  Mark node as group label. [optional]
   */
  isGroupLabel?: boolean;
}

/**
 * @interface TNavigationnode
 *  Item of the navigation tree.
 */
export interface TNavigationnode {
  /**
   *  Id of the node.
   */
  id?: string;
  /**
   *  String representation of the node.
   */
  display_name?: string;
  /**
   *  Children of this node.
   */
  children?: TNavigationnode[];
  /**
   *  Node is open or not.
   */
  open?: boolean;
  /**
   *  Secondary text of the node. [optional]
   */
  secondary_text?: string;
  /**
   *  Searchable description of the node. [optional]
   */
  description?: string;
  /**
   *  Icon of the node. [optional]
   */
  icon?: string;
  /**
   *  Searchable key words of the node. [optional]
   */
  key_words?: string;
  /**
   *  Error indicator. [optional]
   */
  has_error?: boolean;
  /**
   *  Mark node as group label. [optional]
   */
  is_group_label?: boolean;
}

/**
 * Navigationnode
 *  Item of the navigation tree.
 */
export class Navigationnode extends FieldNode {
  /**
   * Id of the node.
   **/
  private _id: STRING;

  /**
   * String representation of the node.
   **/
  private _displayName: STRING;

  /**
   * Children of this node.
   **/
  private _children: ARRAY<Navigationnode, INavigationnode>;

  /**
   * Node is open or not.
   **/
  private _open: BOOLEAN;

  /**
   * Secondary text of the node. [optional]
   **/
  private _secondaryText: STRING;

  /**
   * Searchable description of the node. [optional]
   **/
  private _description: STRING;

  /**
   * Icon of the node. [optional]
   **/
  private _icon: STRING;

  /**
   * Searchable key words of the node. [optional]
   **/
  private _keyWords: STRING;

  /**
   * Error indicator. [optional]
   **/
  private _hasError: BOOLEAN;

  /**
   * Mark node as group label. [optional]
   **/
  private _isGroupLabel: BOOLEAN;

  public __defaultValues: INavigationnode;

  constructor(initData?: INavigationnode, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "tree.Navigationnode";
    this.__meta.description = "Navigationnode Item of the navigation tree.";

    this.__meta.nodeFields = [
      {
        fieldName: "id",
        protoName: "id",
        FieldConstructor: STRING,
        constraints: {},
        description: "Id of the node.",
      },
      {
        fieldName: "displayName",
        protoName: "display_name",
        FieldConstructor: STRING,
        constraints: {},
        description: "String representation of the node.",
      },
      {
        fieldName: "children",
        protoName: "children",
        FieldConstructor: Navigationnode,
        constraints: {},
        description: "Children of this node.",
      },
      {
        fieldName: "open",
        protoName: "open",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "Node is open or not.",
      },
      {
        fieldName: "secondaryText",
        protoName: "secondary_text",
        FieldConstructor: STRING,
        constraints: {},
        description: "Secondary text of the node. [optional]",
      },
      {
        fieldName: "description",
        protoName: "description",
        FieldConstructor: STRING,
        constraints: {},
        description: "Searchable description of the node. [optional]",
      },
      {
        fieldName: "icon",
        protoName: "icon",
        FieldConstructor: STRING,
        constraints: {},
        description: "Icon of the node. [optional]",
      },
      {
        fieldName: "keyWords",
        protoName: "key_words",
        FieldConstructor: STRING,
        constraints: {},
        description: "Searchable key words of the node. [optional]",
      },
      {
        fieldName: "hasError",
        protoName: "has_error",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "Error indicator. [optional]",
      },
      {
        fieldName: "isGroupLabel",
        protoName: "is_group_label",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "Mark node as group label. [optional]",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  Id of the node.
     **/
    this._id = new STRING(undefined, this, "id");

    /**
     *  String representation of the node.
     **/
    this._displayName = new STRING(undefined, this, "displayName");

    /**
     *  Children of this node.
     **/
    this._children = new ARRAY<Navigationnode, INavigationnode>(undefined, this, "children");

    /**
     *  Node is open or not.
     **/
    this._open = new BOOLEAN(undefined, this, "open");

    /**
     *  Secondary text of the node. [optional]
     **/
    this._secondaryText = new STRING(undefined, this, "secondaryText");

    /**
     *  Searchable description of the node. [optional]
     **/
    this._description = new STRING(undefined, this, "description");

    /**
     *  Icon of the node. [optional]
     **/
    this._icon = new STRING(undefined, this, "icon");

    /**
     *  Searchable key words of the node. [optional]
     **/
    this._keyWords = new STRING(undefined, this, "keyWords");

    /**
     *  Error indicator. [optional]
     **/
    this._hasError = new BOOLEAN(undefined, this, "hasError");

    /**
     *  Mark node as group label. [optional]
     **/
    this._isGroupLabel = new BOOLEAN(undefined, this, "isGroupLabel");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof Navigationnode] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof Navigationnode] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Id of the node.
   * The getter receives the FieldNode
   **/
  public get id(): STRING {
    return this._id;
  }

  /**
   * The setter receives `string`
   **/
  public set id(v: string) {
    this.__PrimitivesSetter(this._id, v);
  }

  /**
   *  String representation of the node.
   * The getter receives the FieldNode
   **/
  public get displayName(): STRING {
    return this._displayName;
  }

  /**
   * The setter receives `string`
   **/
  public set displayName(v: string) {
    this.__PrimitivesSetter(this._displayName, v);
  }

  /**
   *  Children of this node.
   * The getter receives the FieldNode
   **/
  public get children(): ARRAY<Navigationnode, INavigationnode> {
    return this._children;
  }

  /**
   * The setter receives `INavigationnode[]`
   **/
  public set children(v: INavigationnode[]) {
    this.__TypeSetter(this._children, v);
  }

  /**
   *  Node is open or not.
   * The getter receives the FieldNode
   **/
  public get open(): BOOLEAN {
    return this._open;
  }

  /**
   * The setter receives `boolean`
   **/
  public set open(v: boolean) {
    this.__PrimitivesSetter(this._open, v);
  }

  /**
   *  Secondary text of the node. [optional]
   * The getter receives the FieldNode
   **/
  public get secondaryText(): STRING {
    return this._secondaryText;
  }

  /**
   * The setter receives `string`
   **/
  public set secondaryText(v: string) {
    this.__PrimitivesSetter(this._secondaryText, v);
  }

  /**
   *  Searchable description of the node. [optional]
   * The getter receives the FieldNode
   **/
  public get description(): STRING {
    return this._description;
  }

  /**
   * The setter receives `string`
   **/
  public set description(v: string) {
    this.__PrimitivesSetter(this._description, v);
  }

  /**
   *  Icon of the node. [optional]
   * The getter receives the FieldNode
   **/
  public get icon(): STRING {
    return this._icon;
  }

  /**
   * The setter receives `string`
   **/
  public set icon(v: string) {
    this.__PrimitivesSetter(this._icon, v);
  }

  /**
   *  Searchable key words of the node. [optional]
   * The getter receives the FieldNode
   **/
  public get keyWords(): STRING {
    return this._keyWords;
  }

  /**
   * The setter receives `string`
   **/
  public set keyWords(v: string) {
    this.__PrimitivesSetter(this._keyWords, v);
  }

  /**
   *  Error indicator. [optional]
   * The getter receives the FieldNode
   **/
  public get hasError(): BOOLEAN {
    return this._hasError;
  }

  /**
   * The setter receives `boolean`
   **/
  public set hasError(v: boolean) {
    this.__PrimitivesSetter(this._hasError, v);
  }

  /**
   *  Mark node as group label. [optional]
   * The getter receives the FieldNode
   **/
  public get isGroupLabel(): BOOLEAN {
    return this._isGroupLabel;
  }

  /**
   * The setter receives `boolean`
   **/
  public set isGroupLabel(v: boolean) {
    this.__PrimitivesSetter(this._isGroupLabel, v);
  }

  fromLiteral(data: INavigationnode): void {
    super.__fromLiteral(data);
  }

  toLiteral(): INavigationnode {
    return super.__toLiteral() as INavigationnode;
  }
}

Registry.register("tree.Navigationnode", Navigationnode);
