// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { BOOLEAN, FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface IFeatureToggle
 *  FeatureToggle is the state for a feature toggle identified by the key field
 */
export interface IFeatureToggle {
  /**
   *  Id of the furo.FeatureToggle.
   */
  key?: string;
  /**
   *  True for allowed, false for denied.
   */
  state?: boolean;
}

/**
 * @interface TFeatureToggle
 *  FeatureToggle is the state for a feature toggle identified by the key field
 */
export interface TFeatureToggle {
  /**
   *  Id of the furo.FeatureToggle.
   */
  key?: string;
  /**
   *  True for allowed, false for denied.
   */
  state?: boolean;
}

/**
 * FeatureToggle
 *  FeatureToggle is the state for a feature toggle identified by the key field
 */
export class FeatureToggle extends FieldNode {
  /**
   * Id of the furo.FeatureToggle.
   **/
  private _key: STRING;

  /**
   * True for allowed, false for denied.
   **/
  private _state: BOOLEAN;

  public __defaultValues: IFeatureToggle;

  constructor(initData?: IFeatureToggle, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.FeatureToggle";
    this.__meta.description = "FeatureToggle FeatureToggle is the state for a feature toggle identified by the key field";

    this.__meta.nodeFields = [
      {
        fieldName: "key",
        protoName: "key",
        FieldConstructor: STRING,
        constraints: {},
        description: "Id of the furo.FeatureToggle.",
      },
      {
        fieldName: "state",
        protoName: "state",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "True for allowed, false for denied.",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  Id of the furo.FeatureToggle.
     **/
    this._key = new STRING(undefined, this, "key");

    /**
     *  True for allowed, false for denied.
     **/
    this._state = new BOOLEAN(undefined, this, "state");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof FeatureToggle] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof FeatureToggle] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  Id of the furo.FeatureToggle.
   * The getter receives the FieldNode
   **/
  public get key(): STRING {
    return this._key;
  }

  /**
   * The setter receives `string`
   **/
  public set key(v: string) {
    this.__PrimitivesSetter(this._key, v);
  }

  /**
   *  True for allowed, false for denied.
   * The getter receives the FieldNode
   **/
  public get state(): BOOLEAN {
    return this._state;
  }

  /**
   * The setter receives `boolean`
   **/
  public set state(v: boolean) {
    this.__PrimitivesSetter(this._state, v);
  }

  fromLiteral(data: IFeatureToggle): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IFeatureToggle {
    return super.__toLiteral() as IFeatureToggle;
  }
}

Registry.register("furo.FeatureToggle", FeatureToggle);
