// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ANY, BOOLEAN, FieldNode, Registry, STRING, type IAny } from "@furo/open-models/dist/index";

import { Fieldoption as FuroFieldoption, type IFieldoption as IFuroFieldoption, type TFieldoption as TFuroFieldoption } from "./Fieldoption";

/**
 * @interface IFieldMeta
 *  Metas for a field
 */
export interface IFieldMeta {
  /**
   *  The default value as JSON string, this must match with the data structure of your type
   */
  default?: string;
  /**
   *  Informative text which can be displayed on the ui
   */
  placeholder?: string;
  /**
   *  A hint
   */
  hint?: string;
  /**
   *  Informative text which can be displayed on the ui
   */
  label?: string;
  /**
   *  Fieldoptions
   */
  options?: IFuroFieldoption;
  /**
   *  Marks the field as readonly. Used for validations.
   */
  readonly?: boolean;
  /**
   *  repeated
   */
  repeated?: boolean;
  /**
   *  Put in type specific metas for your fields here
   */
  typespecific?: IAny;
}

/**
 * @interface TFieldMeta
 *  Metas for a field
 */
export interface TFieldMeta {
  /**
   *  The default value as JSON string, this must match with the data structure of your type
   */
  default?: string;
  /**
   *  Informative text which can be displayed on the ui
   */
  placeholder?: string;
  /**
   *  A hint
   */
  hint?: string;
  /**
   *  Informative text which can be displayed on the ui
   */
  label?: string;
  /**
   *  Fieldoptions
   */
  options?: TFuroFieldoption;
  /**
   *  Marks the field as readonly. Used for validations.
   */
  readonly?: boolean;
  /**
   *  repeated
   */
  repeated?: boolean;
  /**
   *  Put in type specific metas for your fields here
   */
  typespecific?: IAny;
}

/**
 * FieldMeta
 *  Metas for a field
 */
export class FieldMeta extends FieldNode {
  /**
   * The default value as JSON string, this must match with the data structure of your type
   **/
  private _default: STRING;

  /**
   * Informative text which can be displayed on the ui
   **/
  private _placeholder: STRING;

  /**
   * A hint
   **/
  private _hint: STRING;

  /**
   * Informative text which can be displayed on the ui
   **/
  private _label: STRING;

  /**
   * Fieldoptions
   **/
  private _options: FuroFieldoption;

  /**
   * Marks the field as readonly. Used for validations.
   **/
  private _readonly: BOOLEAN;

  /**
   * repeated
   **/
  private _repeated: BOOLEAN;

  /**
   * Put in type specific metas for your fields here
   **/
  private _typespecific: ANY;

  public __defaultValues: IFieldMeta;

  constructor(initData?: IFieldMeta, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.FieldMeta";
    this.__meta.description = "FieldMeta Metas for a field";

    this.__meta.nodeFields = [
      {
        fieldName: "default",
        protoName: "default",
        FieldConstructor: STRING,
        constraints: {},
        description: "The default value as JSON string, this must match with the data structure of your type",
      },
      {
        fieldName: "placeholder",
        protoName: "placeholder",
        FieldConstructor: STRING,
        constraints: {},
        description: "Informative text which can be displayed on the ui",
      },
      {
        fieldName: "hint",
        protoName: "hint",
        FieldConstructor: STRING,
        constraints: {},
        description: "A hint",
      },
      {
        fieldName: "label",
        protoName: "label",
        FieldConstructor: STRING,
        constraints: {},
        description: "Informative text which can be displayed on the ui",
      },
      {
        fieldName: "options",
        protoName: "options",
        FieldConstructor: FuroFieldoption,
        constraints: {},
        description: "Fieldoptions",
      },
      {
        fieldName: "readonly",
        protoName: "readonly",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "Marks the field as readonly. Used for validations.",
      },
      {
        fieldName: "repeated",
        protoName: "repeated",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "repeated",
      },
      {
        fieldName: "typespecific",
        protoName: "typespecific",
        FieldConstructor: ANY,
        constraints: {},
        description: "Put in type specific metas for your fields here",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  The default value as JSON string, this must match with the data structure of your type
     **/
    this._default = new STRING(undefined, this, "default");

    /**
     *  Informative text which can be displayed on the ui
     **/
    this._placeholder = new STRING(undefined, this, "placeholder");

    /**
     *  A hint
     **/
    this._hint = new STRING(undefined, this, "hint");

    /**
     *  Informative text which can be displayed on the ui
     **/
    this._label = new STRING(undefined, this, "label");

    /**
     *  Fieldoptions
     **/
    this._options = new FuroFieldoption(undefined, this, "options");

    /**
     *  Marks the field as readonly. Used for validations.
     **/
    this._readonly = new BOOLEAN(undefined, this, "readonly");

    /**
     *  repeated
     **/
    this._repeated = new BOOLEAN(undefined, this, "repeated");

    /**
     *  Put in type specific metas for your fields here
     **/
    this._typespecific = new ANY(undefined, this, "typespecific");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof FieldMeta] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof FieldMeta] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  The default value as JSON string, this must match with the data structure of your type
   * The getter receives the FieldNode
   **/
  public get default(): STRING {
    return this._default;
  }

  /**
   * The setter receives `string`
   **/
  public set default(v: string) {
    this.__PrimitivesSetter(this._default, v);
  }

  /**
   *  Informative text which can be displayed on the ui
   * The getter receives the FieldNode
   **/
  public get placeholder(): STRING {
    return this._placeholder;
  }

  /**
   * The setter receives `string`
   **/
  public set placeholder(v: string) {
    this.__PrimitivesSetter(this._placeholder, v);
  }

  /**
   *  A hint
   * The getter receives the FieldNode
   **/
  public get hint(): STRING {
    return this._hint;
  }

  /**
   * The setter receives `string`
   **/
  public set hint(v: string) {
    this.__PrimitivesSetter(this._hint, v);
  }

  /**
   *  Informative text which can be displayed on the ui
   * The getter receives the FieldNode
   **/
  public get label(): STRING {
    return this._label;
  }

  /**
   * The setter receives `string`
   **/
  public set label(v: string) {
    this.__PrimitivesSetter(this._label, v);
  }

  /**
   *  Fieldoptions
   * The getter receives the FieldNode
   **/
  public get options(): FuroFieldoption {
    return this._options;
  }

  /**
   * The setter receives `IFuroFieldoption`
   **/
  public set options(v: IFuroFieldoption) {
    this.__TypeSetter(this._options, v);
  }

  /**
   *  Marks the field as readonly. Used for validations.
   * The getter receives the FieldNode
   **/
  public get readonly(): BOOLEAN {
    return this._readonly;
  }

  /**
   * The setter receives `boolean`
   **/
  public set readonly(v: boolean) {
    this.__PrimitivesSetter(this._readonly, v);
  }

  /**
   *  repeated
   * The getter receives the FieldNode
   **/
  public get repeated(): BOOLEAN {
    return this._repeated;
  }

  /**
   * The setter receives `boolean`
   **/
  public set repeated(v: boolean) {
    this.__PrimitivesSetter(this._repeated, v);
  }

  /**
   *  Put in type specific metas for your fields here
   * The getter receives the FieldNode
   **/
  public get typespecific(): ANY {
    return this._typespecific;
  }

  /**
   * The setter receives `IAny`
   **/
  public set typespecific(v: IAny) {
    this.__TypeSetter(this._typespecific, v);
  }

  fromLiteral(data: IFieldMeta): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IFieldMeta {
    return super.__toLiteral() as IFieldMeta;
  }
}

Registry.register("furo.FieldMeta", FieldMeta);
