// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ANY, FieldNode, Registry, STRING, type IAny } from "@furo/open-models/dist/index";

/**
 * @interface IMCFieldViolation
 *  Field violation with user response
 */
export interface IMCFieldViolation {
  /**
   *  A path leading to a field in the request body. The value will be a
   *  sequence of dot-separated identifiers that identify a protocol buffer
   *  field.
   */
  field?: string;
  /**
   *  A localized description of why the request element is bad.
   */
  description?: string;
  /**
   *  Optional user confirmation response, can be a text, checkbox,... is displayed as typerenderer
   */
  userResponse?: IAny;
  /**
   *  Extended message for the field violation.
   */
  message?: string;
}

/**
 * @interface TMCFieldViolation
 *  Field violation with user response
 */
export interface TMCFieldViolation {
  /**
   *  A path leading to a field in the request body. The value will be a
   *  sequence of dot-separated identifiers that identify a protocol buffer
   *  field.
   */
  field?: string;
  /**
   *  A localized description of why the request element is bad.
   */
  description?: string;
  /**
   *  Optional user confirmation response, can be a text, checkbox,... is displayed as typerenderer
   */
  user_response?: IAny;
  /**
   *  Extended message for the field violation.
   */
  message?: string;
}

/**
 * MCFieldViolation
 *  Field violation with user response
 */
export class MCFieldViolation extends FieldNode {
  /**
   * A path leading to a field in the request body. The value will be a
   * sequence of dot-separated identifiers that identify a protocol buffer
   * field.
   **/
  private _field: STRING;

  /**
   * A localized description of why the request element is bad.
   **/
  private _description: STRING;

  /**
   * Optional user confirmation response, can be a text, checkbox,... is displayed as typerenderer
   **/
  private _userResponse: ANY;

  /**
   * Extended message for the field violation.
   **/
  private _message: STRING;

  public __defaultValues: IMCFieldViolation;

  constructor(initData?: IMCFieldViolation, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.MCFieldViolation";
    this.__meta.description = "MCFieldViolation Field violation with user response";

    this.__meta.nodeFields = [
      {
        fieldName: "field",
        protoName: "field",
        FieldConstructor: STRING,
        constraints: {},
        description:
          "A path leading to a field in the request body. The value will be a\n sequence of dot-separated identifiers that identify a protocol buffer\n field.",
      },
      {
        fieldName: "description",
        protoName: "description",
        FieldConstructor: STRING,
        constraints: {},
        description: "A localized description of why the request element is bad.",
      },
      {
        fieldName: "userResponse",
        protoName: "user_response",
        FieldConstructor: ANY,
        constraints: {},
        description: "Optional user confirmation response, can be a text, checkbox,... is displayed as typerenderer",
      },
      {
        fieldName: "message",
        protoName: "message",
        FieldConstructor: STRING,
        constraints: {},
        description: "Extended message for the field violation.",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  A path leading to a field in the request body. The value will be a
     *  sequence of dot-separated identifiers that identify a protocol buffer
     *  field.
     **/
    this._field = new STRING(undefined, this, "field");

    /**
     *  A localized description of why the request element is bad.
     **/
    this._description = new STRING(undefined, this, "description");

    /**
     *  Optional user confirmation response, can be a text, checkbox,... is displayed as typerenderer
     **/
    this._userResponse = new ANY(undefined, this, "userResponse");

    /**
     *  Extended message for the field violation.
     **/
    this._message = new STRING(undefined, this, "message");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof MCFieldViolation] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof MCFieldViolation] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  A path leading to a field in the request body. The value will be a
   *  sequence of dot-separated identifiers that identify a protocol buffer
   *  field.
   * The getter receives the FieldNode
   **/
  public get field(): STRING {
    return this._field;
  }

  /**
   * The setter receives `string`
   **/
  public set field(v: string) {
    this.__PrimitivesSetter(this._field, v);
  }

  /**
   *  A localized description of why the request element is bad.
   * The getter receives the FieldNode
   **/
  public get description(): STRING {
    return this._description;
  }

  /**
   * The setter receives `string`
   **/
  public set description(v: string) {
    this.__PrimitivesSetter(this._description, v);
  }

  /**
   *  Optional user confirmation response, can be a text, checkbox,... is displayed as typerenderer
   * The getter receives the FieldNode
   **/
  public get userResponse(): ANY {
    return this._userResponse;
  }

  /**
   * The setter receives `IAny`
   **/
  public set userResponse(v: IAny) {
    this.__TypeSetter(this._userResponse, v);
  }

  /**
   *  Extended message for the field violation.
   * The getter receives the FieldNode
   **/
  public get message(): STRING {
    return this._message;
  }

  /**
   * The setter receives `string`
   **/
  public set message(v: string) {
    this.__PrimitivesSetter(this._message, v);
  }

  fromLiteral(data: IMCFieldViolation): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IMCFieldViolation {
    return super.__toLiteral() as IMCFieldViolation;
  }
}

Registry.register("furo.MCFieldViolation", MCFieldViolation);
