// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

/**
 * @interface IStringOptionProperty
 *  String type to use in property
 */
export interface IStringOptionProperty {
  /**
   *  String representation of val
   */
  displayName?: string;
  /**
   *  The value, Id is used to make working with data-inputs easier
   */
  id?: string;
}

/**
 * @interface TStringOptionProperty
 *  String type to use in property
 */
export interface TStringOptionProperty {
  /**
   *  String representation of val
   */
  display_name?: string;
  /**
   *  The value, Id is used to make working with data-inputs easier
   */
  id?: string;
}

/**
 * StringOptionProperty
 *  String type to use in property
 */
export class StringOptionProperty extends FieldNode {
  /**
   * String representation of val
   **/
  private _displayName: STRING;

  /**
   * The value, Id is used to make working with data-inputs easier
   **/
  private _id: STRING;

  public __defaultValues: IStringOptionProperty;

  constructor(initData?: IStringOptionProperty, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "furo.StringOptionProperty";
    this.__meta.description = "StringOptionProperty String type to use in property";

    this.__meta.nodeFields = [
      {
        fieldName: "displayName",
        protoName: "display_name",
        FieldConstructor: STRING,
        constraints: {},
        description: "String representation of val",
      },
      {
        fieldName: "id",
        protoName: "id",
        FieldConstructor: STRING,
        constraints: {},
        description: "The value, Id is used to make working with data-inputs easier",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  String representation of val
     **/
    this._displayName = new STRING(undefined, this, "displayName");

    /**
     *  The value, Id is used to make working with data-inputs easier
     **/
    this._id = new STRING(undefined, this, "id");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof StringOptionProperty] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof StringOptionProperty] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  String representation of val
   * The getter receives the FieldNode
   **/
  public get displayName(): STRING {
    return this._displayName;
  }

  /**
   * The setter receives `string`
   **/
  public set displayName(v: string) {
    this.__PrimitivesSetter(this._displayName, v);
  }

  /**
   *  The value, Id is used to make working with data-inputs easier
   * The getter receives the FieldNode
   **/
  public get id(): STRING {
    return this._id;
  }

  /**
   * The setter receives `string`
   **/
  public set id(v: string) {
    this.__PrimitivesSetter(this._id, v);
  }

  fromLiteral(data: IStringOptionProperty): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IStringOptionProperty {
    return super.__toLiteral() as IStringOptionProperty;
  }
}

Registry.register("furo.StringOptionProperty", StringOptionProperty);
