// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { BOOLEAN, FieldNode, Registry } from "@furo/open-models/dist/index";

/**
 * @interface IBoolValue
 *  Wrapper message for `bool`.
 *
 *  The JSON representation for `BoolValue` is JSON `true` and `false`.
 */
export interface IBoolValue {
  /**
   *  The bool value.
   */
  value?: boolean;
}

/**
 * @interface TBoolValue
 *  Wrapper message for `bool`.
 *
 *  The JSON representation for `BoolValue` is JSON `true` and `false`.
 */
export interface TBoolValue {
  /**
   *  The bool value.
   */
  value?: boolean;
}

/**
 * BoolValue
 *  Wrapper message for `bool`.
 *
 *  The JSON representation for `BoolValue` is JSON `true` and `false`.
 */
export class BoolValue extends FieldNode {
  /**
   * The bool value.
   **/
  private _value: BOOLEAN;

  public __defaultValues: IBoolValue;

  constructor(initData?: IBoolValue, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "google.protobuf.BoolValue";
    this.__meta.description = "BoolValue Wrapper message for `bool`.\n\n The JSON representation for `BoolValue` is JSON `true` and `false`.";

    this.__meta.nodeFields = [
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: BOOLEAN,
        constraints: {},
        description: "The bool value.",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  The bool value.
     **/
    this._value = new BOOLEAN(undefined, this, "value");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof BoolValue] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof BoolValue] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  The bool value.
   * The getter receives the FieldNode
   **/
  public get value(): BOOLEAN {
    return this._value;
  }

  /**
   * The setter receives `boolean`
   **/
  public set value(v: boolean) {
    this.__PrimitivesSetter(this._value, v);
  }

  fromLiteral(data: IBoolValue): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IBoolValue {
    return super.__toLiteral() as IBoolValue;
  }
}

Registry.register("google.protobuf.BoolValue", BoolValue);
