// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ARRAY, BOOLEAN, FieldNode, Registry } from "@furo/open-models/dist/index";

import {
  FeatureSet as GoogleProtobufFeatureSet,
  type IFeatureSet as IGoogleProtobufFeatureSet,
  type TFeatureSet as TGoogleProtobufFeatureSet,
} from "./FeatureSet";
import {
  UninterpretedOption as GoogleProtobufUninterpretedOption,
  type IUninterpretedOption as IGoogleProtobufUninterpretedOption,
  type TUninterpretedOption as TGoogleProtobufUninterpretedOption,
} from "./UninterpretedOption";

/**
 * @interface IEnumValueOptions
 */
export interface IEnumValueOptions {
  /**
   *  Is this enum value deprecated?
   *  Depending on the target platform, this can emit Deprecated annotations
   *  for the enum value, or it will be completely ignored; in the very least,
   *  this is a formalization for deprecating enum values.
   */
  deprecated?: boolean;
  /**
   *  Any features defined in the specific edition.
   */
  features?: IGoogleProtobufFeatureSet;
  /**
   *  Indicate that fields annotated with this enum value should not be printed
   *  out when using debug formats, e.g. when the field contains sensitive
   *  credentials.
   */
  debugRedact?: boolean;
  /**
   *  The parser stores options it doesn't recognize here. See above.
   */
  uninterpretedOption?: IGoogleProtobufUninterpretedOption[];
}

/**
 * @interface TEnumValueOptions
 */
export interface TEnumValueOptions {
  /**
   *  Is this enum value deprecated?
   *  Depending on the target platform, this can emit Deprecated annotations
   *  for the enum value, or it will be completely ignored; in the very least,
   *  this is a formalization for deprecating enum values.
   */
  deprecated?: boolean;
  /**
   *  Any features defined in the specific edition.
   */
  features?: TGoogleProtobufFeatureSet;
  /**
   *  Indicate that fields annotated with this enum value should not be printed
   *  out when using debug formats, e.g. when the field contains sensitive
   *  credentials.
   */
  debug_redact?: boolean;
  /**
   *  The parser stores options it doesn't recognize here. See above.
   */
  uninterpreted_option?: TGoogleProtobufUninterpretedOption[];
}

/**
 * EnumValueOptions
 */
export class EnumValueOptions extends FieldNode {
  //  Is this enum value deprecated?
  //  Depending on the target platform, this can emit Deprecated annotations
  //  for the enum value, or it will be completely ignored; in the very least,
  //  this is a formalization for deprecating enum values.
  private _deprecated: BOOLEAN;

  //  Any features defined in the specific edition.
  private _features: GoogleProtobufFeatureSet;

  //  Indicate that fields annotated with this enum value should not be printed
  //  out when using debug formats, e.g. when the field contains sensitive
  //  credentials.
  private _debugRedact: BOOLEAN;

  //  The parser stores options it doesn't recognize here. See above.
  private _uninterpretedOption: ARRAY<GoogleProtobufUninterpretedOption, IGoogleProtobufUninterpretedOption>;

  public __defaultValues: IEnumValueOptions;

  constructor(initData?: IEnumValueOptions, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "google.protobuf.EnumValueOptions";

    this.__meta.nodeFields = [
      {
        fieldName: "deprecated",
        protoName: "deprecated",
        FieldConstructor: BOOLEAN,
        constraints: {},
      },
      {
        fieldName: "features",
        protoName: "features",
        FieldConstructor: GoogleProtobufFeatureSet,
        constraints: {},
      },
      {
        fieldName: "debugRedact",
        protoName: "debug_redact",
        FieldConstructor: BOOLEAN,
        constraints: {},
      },
      {
        fieldName: "uninterpretedOption",
        protoName: "uninterpreted_option",
        FieldConstructor: GoogleProtobufUninterpretedOption,
        constraints: {},
      },
    ];

    // Initialize the fields
    //  Is this enum value deprecated?
    //  Depending on the target platform, this can emit Deprecated annotations
    //  for the enum value, or it will be completely ignored; in the very least,
    //  this is a formalization for deprecating enum values.
    this._deprecated = new BOOLEAN(undefined, this, "deprecated");

    //  Any features defined in the specific edition.
    this._features = new GoogleProtobufFeatureSet(undefined, this, "features");

    //  Indicate that fields annotated with this enum value should not be printed
    //  out when using debug formats, e.g. when the field contains sensitive
    //  credentials.
    this._debugRedact = new BOOLEAN(undefined, this, "debugRedact");

    //  The parser stores options it doesn't recognize here. See above.
    this._uninterpretedOption = new ARRAY<GoogleProtobufUninterpretedOption, IGoogleProtobufUninterpretedOption>(undefined, this, "uninterpretedOption");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof EnumValueOptions] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof EnumValueOptions] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  //  Is this enum value deprecated?
  //  Depending on the target platform, this can emit Deprecated annotations
  //  for the enum value, or it will be completely ignored; in the very least,
  //  this is a formalization for deprecating enum values.
  public get deprecated(): BOOLEAN {
    return this._deprecated;
  }

  public set deprecated(v: boolean) {
    this.__PrimitivesSetter(this._deprecated, v);
  }

  //  Any features defined in the specific edition.
  public get features(): GoogleProtobufFeatureSet {
    return this._features;
  }

  public set features(v: IGoogleProtobufFeatureSet) {
    this.__TypeSetter(this._features, v);
  }

  //  Indicate that fields annotated with this enum value should not be printed
  //  out when using debug formats, e.g. when the field contains sensitive
  //  credentials.
  public get debugRedact(): BOOLEAN {
    return this._debugRedact;
  }

  public set debugRedact(v: boolean) {
    this.__PrimitivesSetter(this._debugRedact, v);
  }

  //  The parser stores options it doesn't recognize here. See above.
  public get uninterpretedOption(): ARRAY<GoogleProtobufUninterpretedOption, IGoogleProtobufUninterpretedOption> {
    return this._uninterpretedOption;
  }

  public set uninterpretedOption(v: IGoogleProtobufUninterpretedOption[]) {
    this.__TypeSetter(this._uninterpretedOption, v);
  }

  fromLiteral(data: IEnumValueOptions) {
    super.__fromLiteral(data);
  }

  toLiteral(): IEnumValueOptions {
    return super.__toLiteral();
  }
}

Registry.register("google.protobuf.EnumValueOptions", EnumValueOptions);
