// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import type { FieldNode } from "@furo/open-models/dist/index";
import { ENUM } from "@furo/open-models/dist/index";

export enum FeatureSetEnumType {
  ENUM_TYPE_UNKNOWN = "ENUM_TYPE_UNKNOWN",
  OPEN = "OPEN",
  CLOSED = "CLOSED",
}

/**
 * FieldNode for FeatureSetEnumType.
 * Used as the element constructor of ARRAY and the value constructor of MAP,
 * which both build their children with `new Constructor()`.
 **/
export class FeatureSetEnumTypeENUM extends ENUM<FeatureSetEnumType> {
  constructor(initData?: FeatureSetEnumType, parent?: FieldNode, parentAttributeName?: string) {
    super(initData, FeatureSetEnumType, FeatureSetEnumType.ENUM_TYPE_UNKNOWN, parent, parentAttributeName);
  }
}
