// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import type { FieldNode } from "@furo/open-models/dist/index";
import { ENUM } from "@furo/open-models/dist/index";

export enum FeatureSetMessageEncoding {
  MESSAGE_ENCODING_UNKNOWN = "MESSAGE_ENCODING_UNKNOWN",
  LENGTH_PREFIXED = "LENGTH_PREFIXED",
  DELIMITED = "DELIMITED",
}

/**
 * FieldNode for FeatureSetMessageEncoding.
 * Used as the element constructor of ARRAY and the value constructor of MAP,
 * which both build their children with `new Constructor()`.
 **/
export class FeatureSetMessageEncodingENUM extends ENUM<FeatureSetMessageEncoding> {
  constructor(initData?: FeatureSetMessageEncoding, parent?: FieldNode, parentAttributeName?: string) {
    super(initData, FeatureSetMessageEncoding, FeatureSetMessageEncoding.MESSAGE_ENCODING_UNKNOWN, parent, parentAttributeName);
  }
}
