// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { ARRAY, ENUM, FieldNode, Registry } from "@furo/open-models/dist/index";

import { Edition as GoogleProtobufEdition } from "./Edition";
import {
  FeatureSetDefaultsFeatureSetEditionDefault as GoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault,
  type IFeatureSetDefaultsFeatureSetEditionDefault as IGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault,
  type TFeatureSetDefaultsFeatureSetEditionDefault as TGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault,
} from "./FeatureSetDefaults.FeatureSetEditionDefault";

/**
 * @interface IFeatureSetDefaults
 *  A compiled specification for the defaults of a set of features.  These
 *  messages are generated from FeatureSet extensions and can be used to seed
 *  feature resolution. The resolution with this object becomes a simple search
 *  for the closest matching edition, followed by proto merges.
 */
export interface IFeatureSetDefaults {
  defaults?: IGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault[];
  /**
   *  The minimum supported edition (inclusive) when this was constructed.
   *  Editions before this will not have defaults.
   */
  minimumEdition?: GoogleProtobufEdition | string;
  /**
   *  The maximum known edition (inclusive) when this was constructed. Editions
   *  after this will not have reliable defaults.
   */
  maximumEdition?: GoogleProtobufEdition | string;
}

/**
 * @interface TFeatureSetDefaults
 *  A compiled specification for the defaults of a set of features.  These
 *  messages are generated from FeatureSet extensions and can be used to seed
 *  feature resolution. The resolution with this object becomes a simple search
 *  for the closest matching edition, followed by proto merges.
 */
export interface TFeatureSetDefaults {
  defaults?: TGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault[];
  /**
   *  The minimum supported edition (inclusive) when this was constructed.
   *  Editions before this will not have defaults.
   */
  minimum_edition?: GoogleProtobufEdition | string;
  /**
   *  The maximum known edition (inclusive) when this was constructed. Editions
   *  after this will not have reliable defaults.
   */
  maximum_edition?: GoogleProtobufEdition | string;
}

/**
 * FeatureSetDefaults
 *  A compiled specification for the defaults of a set of features.  These
 *  messages are generated from FeatureSet extensions and can be used to seed
 *  feature resolution. The resolution with this object becomes a simple search
 *  for the closest matching edition, followed by proto merges.
 */
export class FeatureSetDefaults extends FieldNode {
  private _defaults: ARRAY<GoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault, IGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault>;

  //  The minimum supported edition (inclusive) when this was constructed.
  //  Editions before this will not have defaults.
  private _minimumEdition: ENUM<GoogleProtobufEdition>;

  //  The maximum known edition (inclusive) when this was constructed. Editions
  //  after this will not have reliable defaults.
  private _maximumEdition: ENUM<GoogleProtobufEdition>;

  public __defaultValues: IFeatureSetDefaults;

  constructor(initData?: IFeatureSetDefaults, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "google.protobuf.FeatureSetDefaults";

    this.__meta.nodeFields = [
      {
        fieldName: "defaults",
        protoName: "defaults",
        FieldConstructor: GoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault,
        constraints: {},
      },
      {
        fieldName: "minimumEdition",
        protoName: "minimum_edition",
        FieldConstructor: ENUM<GoogleProtobufEdition>,
        constraints: {},
      },
      {
        fieldName: "maximumEdition",
        protoName: "maximum_edition",
        FieldConstructor: ENUM<GoogleProtobufEdition>,
        constraints: {},
      },
    ];

    // Initialize the fields
    this._defaults = new ARRAY<GoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault, IGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault>(
      undefined,
      this,
      "defaults"
    );

    //  The minimum supported edition (inclusive) when this was constructed.
    //  Editions before this will not have defaults.
    this._minimumEdition = new ENUM<GoogleProtobufEdition>(undefined, GoogleProtobufEdition, GoogleProtobufEdition.EDITION_UNKNOWN, this, "minimumEdition");

    //  The maximum known edition (inclusive) when this was constructed. Editions
    //  after this will not have reliable defaults.
    this._maximumEdition = new ENUM<GoogleProtobufEdition>(undefined, GoogleProtobufEdition, GoogleProtobufEdition.EDITION_UNKNOWN, this, "maximumEdition");

    // Set required fields
    [].forEach((fieldName) => {
      (this[fieldName as keyof FeatureSetDefaults] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach((fieldName) => {
      (this[fieldName as keyof FeatureSetDefaults] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  public get defaults(): ARRAY<GoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault, IGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault> {
    return this._defaults;
  }

  public set defaults(v: IGoogleProtobufFeatureSetDefaultsFeatureSetEditionDefault[]) {
    this.__TypeSetter(this._defaults, v);
  }

  //  The minimum supported edition (inclusive) when this was constructed.
  //  Editions before this will not have defaults.
  public get minimumEdition(): ENUM<GoogleProtobufEdition> {
    return this._minimumEdition;
  }

  public set minimumEdition(v: GoogleProtobufEdition) {
    this.__TypeSetter(this._minimumEdition, v);
  }

  //  The maximum known edition (inclusive) when this was constructed. Editions
  //  after this will not have reliable defaults.
  public get maximumEdition(): ENUM<GoogleProtobufEdition> {
    return this._maximumEdition;
  }

  public set maximumEdition(v: GoogleProtobufEdition) {
    this.__TypeSetter(this._maximumEdition, v);
  }

  fromLiteral(data: IFeatureSetDefaults) {
    super.__fromLiteral(data);
  }

  toLiteral(): IFeatureSetDefaults {
    return super.__toLiteral();
  }
}

Registry.register("google.protobuf.FeatureSetDefaults", FeatureSetDefaults);
