// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FLOAT, FieldNode, Registry } from "@furo/open-models/dist/index";

/**
 * @interface IFloatValue
 *  Wrapper message for `float`.
 *
 *  The JSON representation for `FloatValue` is JSON number.
 */
export interface IFloatValue {
  /**
   *  The float value.
   */
  value?: number;
}

/**
 * @interface TFloatValue
 *  Wrapper message for `float`.
 *
 *  The JSON representation for `FloatValue` is JSON number.
 */
export interface TFloatValue {
  /**
   *  The float value.
   */
  value?: number;
}

/**
 * FloatValue
 *  Wrapper message for `float`.
 *
 *  The JSON representation for `FloatValue` is JSON number.
 */
export class FloatValue extends FieldNode {
  /**
   * The float value.
   **/
  private _value: FLOAT;

  public __defaultValues: IFloatValue;

  constructor(initData?: IFloatValue, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "google.protobuf.FloatValue";
    this.__meta.description = "FloatValue Wrapper message for `float`.\n\n The JSON representation for `FloatValue` is JSON number.";

    this.__meta.nodeFields = [
      {
        fieldName: "value",
        protoName: "value",
        FieldConstructor: FLOAT,
        constraints: {},
        description: "The float value.",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     *  The float value.
     **/
    this._value = new FLOAT(undefined, this, "value");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof FloatValue] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof FloatValue] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   *  The float value.
   * The getter receives the FieldNode
   **/
  public get value(): FLOAT {
    return this._value;
  }

  /**
   * The setter receives `number`
   **/
  public set value(v: number) {
    this.__PrimitivesSetter(this._value, v);
  }

  fromLiteral(data: IFloatValue): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IFloatValue {
    return super.__toLiteral() as IFloatValue;
  }
}

Registry.register("google.protobuf.FloatValue", FloatValue);
