// Code generated by furo protoc-gen-open-models. DO NOT EDIT.
// protoc-gen-open-models version: ????

import { FieldNode, Registry, STRING } from "@furo/open-models/dist/index";

import {
  OneofOptions as GoogleProtobufOneofOptions,
  type IOneofOptions as IGoogleProtobufOneofOptions,
  type TOneofOptions as TGoogleProtobufOneofOptions,
} from "./OneofOptions";

/**
 * @interface IOneofDescriptorProto
 *  Describes a oneof.
 */
export interface IOneofDescriptorProto {
  name?: string;
  options?: IGoogleProtobufOneofOptions;
}

/**
 * @interface TOneofDescriptorProto
 *  Describes a oneof.
 */
export interface TOneofDescriptorProto {
  name?: string;
  options?: TGoogleProtobufOneofOptions;
}

/**
 * OneofDescriptorProto
 *  Describes a oneof.
 */
export class OneofDescriptorProto extends FieldNode {
  /**
   **/
  private _name: STRING;

  /**
   **/
  private _options: GoogleProtobufOneofOptions;

  public __defaultValues: IOneofDescriptorProto;

  constructor(initData?: IOneofDescriptorProto, parent?: FieldNode, parentAttributeName?: string) {
    super(undefined, parent, parentAttributeName);
    this.__meta.typeName = "google.protobuf.OneofDescriptorProto";
    this.__meta.description = "OneofDescriptorProto Describes a oneof.";

    this.__meta.nodeFields = [
      {
        fieldName: "name",
        protoName: "name",
        FieldConstructor: STRING,
        constraints: {},
        description: "",
      },
      {
        fieldName: "options",
        protoName: "options",
        FieldConstructor: GoogleProtobufOneofOptions,
        constraints: {},
        description: "",
      },
    ];

    // Initialize the fields
    // ---------------------

    /**
     **/
    this._name = new STRING(undefined, this, "name");

    /**
     **/
    this._options = new GoogleProtobufOneofOptions(undefined, this, "options");

    // Set required fields
    [].forEach(fieldName => {
      (this[fieldName as keyof OneofDescriptorProto] as FieldNode).__meta.required = true;
    });

    // Default values from openAPI annotations
    this.__defaultValues = {};

    // Initialize the fields with init data
    if (initData !== undefined) {
      this.__fromLiteral({ ...this.__defaultValues, ...initData });
    } else {
      this.__fromLiteral(this.__defaultValues);
    }

    // Set readonly fields after the init, so child nodes are readonly too
    [].forEach(fieldName => {
      (this[fieldName as keyof OneofDescriptorProto] as FieldNode).__readonly = true;
    });

    this.__meta.isPristine = true;
  }

  /**
   * The getter receives the FieldNode
   **/
  public get name(): STRING {
    return this._name;
  }

  /**
   * The setter receives `string`
   **/
  public set name(v: string) {
    this.__PrimitivesSetter(this._name, v);
  }

  /**
   * The getter receives the FieldNode
   **/
  public get options(): GoogleProtobufOneofOptions {
    return this._options;
  }

  /**
   * The setter receives `IGoogleProtobufOneofOptions | null`
   **/
  public set options(v: IGoogleProtobufOneofOptions | null) {
    this.__TypeSetter(this._options, v);
  }

  fromLiteral(data: IOneofDescriptorProto): void {
    super.__fromLiteral(data);
  }

  toLiteral(): IOneofDescriptorProto {
    return super.__toLiteral() as IOneofDescriptorProto;
  }
}

Registry.register("google.protobuf.OneofDescriptorProto", OneofDescriptorProto);
